# Generated by Django 5.0.1 on 2025-10-09 02:08

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        VectorExtension()
    ]
