# Generated by Django 5.0.1 on 2025-10-09 02:08

import apps.kb.models
import django.db.models.deletion
import pgvector.django
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kb", "0001_enable_pgvector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("manual", "Manual/Guia"),
                            ("lei", "Lei/Normativa"),
                            ("exemplo", "Exemplo de ETP"),
                            ("referencia", "Material de Referência"),
                            ("template", "Template"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload de PDF, DOC, DOCX, TXT ou MD",
                        upload_to="kb/documents/",
                        validators=[apps.kb.models.validate_document_file],
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamanho do Arquivo (bytes)"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Tipo de Arquivo"
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, verbose_name="Texto Extraído"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Processado"),
                            ("failed", "Falha no Processamento"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="Erro no Processamento"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processado em"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados extraídos do documento (autor, data, etc)",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de tags para facilitar busca",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Se falso, apenas o criador pode visualizar",
                        verbose_name="Público",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Posição no documento original",
                        verbose_name="Índice do Chunk",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados específicos do chunk (página, seção, etc)",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "token_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Contagem de Tokens"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="kb.document",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk de Documento",
                "verbose_name_plural": "Chunks de Documentos",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category", "is_active"], name="kb_document_categor_ef2b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "created_at"], name="kb_document_status_706293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="kb_document_documen_b3816f_idx",
            ),
        ),
    ]
