# Generated by Django 5.0.1 on 2026-02-07 15:53

import apps.kb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload de PDF, DOC, DOCX, TXT ou MD",
                null=True,
                upload_to="kb/documents/",
                validators=[apps.kb.models.validate_document_file],
                verbose_name="Arquivo",
            ),
        ),
    ]
