# Generated by Django 5.0.1 on 2026-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0003_make_file_optional_for_background_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("processing", "Processando"),
                    ("completed", "Processado"),
                    ("uploading", "Enviando Arquivo"),
                    ("ready", "Finalizado"),
                    ("failed", "Falha no Processamento"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
