# Generated by Django 5.2.11 on 2026-05-25 23:30
# Nota: RenameIndex removidos — índices já existem com os novos nomes (criados pela 0001 com Django 5.x).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='generated_document_id',
            field=models.UUIDField(blank=True, help_text='Referência a GeneratedDocument do intelligent_assistant', null=True, verbose_name='ID do Documento Gerado'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='descricao',
            field=models.TextField(blank=True, help_text='Resumo dos fatos, tese jurídica e estratégia', verbose_name='Descrição do Caso'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='numero_processo',
            field=models.CharField(blank=True, help_text='Formato CNJ: NNNNNNN-DD.AAAA.J.TT.OOOO', max_length=30, verbose_name='Número do Processo'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='titulo',
            field=models.CharField(help_text='Descrição resumida do caso', max_length=255, verbose_name='Título / Assunto'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='tribunal',
            field=models.CharField(blank=True, help_text='Ex: TJRJ, TRT-1, STJ', max_length=100, verbose_name='Tribunal'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='vara_juizo',
            field=models.CharField(blank=True, help_text='Ex: 3ª Vara Cível da Comarca do Rio de Janeiro', max_length=200, verbose_name='Vara / Juízo'),
        ),
    ]
