# Generated by Django 5.0.14 on 2026-05-30 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_casedocument_file_and_tipo_documento_cliente'),
        ('intelligent_assistant', '0043_alter_documentblueprint_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNFSe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_nfse', models.CharField(blank=True, max_length=50, verbose_name='Número NFS-e')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=100, verbose_name='Código de Verificação')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente de Envio'), ('processing', 'Processando'), ('authorized', 'Autorizada'), ('cancelled', 'Cancelada'), ('error', 'Erro')], default='draft', max_length=15)),
                ('descricao_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('codigo_servico', models.CharField(default='6911-7/01', help_text='Atividades jurídicas: 6911-7/01', max_length=20, verbose_name='Código de Serviço CNAE')),
                ('codigo_tributacao', models.CharField(blank=True, max_length=20, verbose_name='Código de Tributação Municipal')),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Serviço (R$)')),
                ('valor_deducoes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deduções (R$)')),
                ('base_calculo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Base de Cálculo')),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Alíquota ISS (%)')),
                ('valor_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor ISS (R$)')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Líquido (R$)')),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IRRF (R$)')),
                ('pis', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PIS (R$)')),
                ('cofins', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='COFINS (R$)')),
                ('csll', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CSLL (R$)')),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='INSS (R$)')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_competencia', models.DateField(verbose_name='Competência')),
                ('municipio_prestacao', models.CharField(max_length=100, verbose_name='Município de Prestação')),
                ('xml_envio', models.TextField(blank=True, verbose_name='XML de Envio')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML de Retorno')),
                ('pdf_url', models.URLField(blank=True, verbose_name='URL do PDF')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Serviço',
                'verbose_name_plural': 'Notas Fiscais de Serviço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('cases_won', models.IntegerField(default=0, verbose_name='Casos Ganhos')),
                ('cases_lost', models.IntegerField(default=0, verbose_name='Casos Perdidos')),
                ('cases_settled', models.IntegerField(default=0, verbose_name='Acordos')),
                ('deadlines_met', models.IntegerField(default=0, verbose_name='Prazos Cumpridos')),
                ('deadlines_missed', models.IntegerField(default=0, verbose_name='Prazos Perdidos')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='Tarefas Concluídas')),
                ('hours_logged', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Registradas')),
                ('documents_generated', models.IntegerField(default=0, verbose_name='Documentos Gerados')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Receita Gerada (R$)')),
                ('client_satisfaction', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Satisfação do Cliente (0-10)')),
                ('total_score', models.IntegerField(default=0, verbose_name='Pontuação Total')),
                ('rank_position', models.IntegerField(blank=True, null=True, verbose_name='Posição no Ranking')),
                ('badges', models.JSONField(blank=True, default=list, verbose_name='Conquistas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pontuação do Advogado',
                'verbose_name_plural': 'Pontuações dos Advogados',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Caso')),
                ('specialty', models.CharField(blank=True, choices=[('civel', 'Cível'), ('criminal', 'Criminal'), ('trabalhista', 'Trabalhista'), ('tributario', 'Tributário'), ('administrativo', 'Administrativo'), ('previdenciario', 'Previdenciário'), ('familia', 'Família e Sucessões'), ('empresarial', 'Empresarial'), ('ambiental', 'Ambiental'), ('consumidor', 'Direito do Consumidor'), ('imobiliario', 'Imobiliário'), ('outros', 'Outros')], max_length=20)),
                ('source', models.CharField(choices=[('indicacao', 'Indicação'), ('site', 'Site'), ('google', 'Google'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('evento', 'Evento'), ('outro', 'Outro')], default='outro', max_length=15, verbose_name='Origem')),
                ('temperature', models.CharField(choices=[('cold', 'Frio'), ('warm', 'Morno'), ('hot', 'Quente')], default='warm', max_length=5, verbose_name='Temperatura')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Estimado (R$)')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Convertido em')),
                ('next_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Contato')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('intake_form_data', models.JSONField(blank=True, default=dict, verbose_name='Dados do Formulário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('call', 'Ligação'), ('email', 'E-mail'), ('meeting', 'Reunião'), ('whatsapp', 'WhatsApp'), ('proposal', 'Proposta Enviada'), ('note', 'Anotação'), ('stage_change', 'Mudança de Etapa')], max_length=15)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atividade do Lead',
                'verbose_name_plural': 'Atividades do Lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Etapa')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor')),
                ('is_won', models.BooleanField(default=False, verbose_name='Etapa de Ganho')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Etapa de Perda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etapa do Funil',
                'verbose_name_plural': 'Etapas do Funil',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Data')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas')),
                ('description', models.TextField(verbose_name='Descrição da Atividade')),
                ('billing_type', models.CharField(choices=[('billable', 'Faturável'), ('non_billable', 'Não Faturável'), ('pro_bono', 'Pro Bono')], default='billable', max_length=15)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor/Hora (R$)')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total (R$)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Horas',
                'verbose_name_plural': 'Registros de Horas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='audiencia',
            new_name='cases_audie_caso_id_c29fc1_idx',
            old_name='cases_audie_caso_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='audiencia',
            new_name='cases_audie_data_ho_8e33f8_idx',
            old_name='cases_audie_data_ho_idx',
        ),
        migrations.RenameIndex(
            model_name='casephase',
            new_name='cases_casep_caso_id_d7e482_idx',
            old_name='cases_casep_caso_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='casetask',
            new_name='cases_caset_caso_id_249916_idx',
            old_name='cases_task_caso_status_idx',
        ),
        migrations.RenameIndex(
            model_name='casetask',
            new_name='cases_caset_respons_8c83f2_idx',
            old_name='cases_task_responsavel_idx',
        ),
        migrations.RenameIndex(
            model_name='casetask',
            new_name='cases_caset_data_li_f321ad_idx',
            old_name='cases_task_data_limite_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='cases_clien_client__ffed22_idx',
            old_name='cases_clien_client__b2e5e7_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='cases_clien_is_acti_a07a24_idx',
            old_name='cases_clien_is_acti_a1c3d4_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='cases_clien_respons_683e6a_idx',
            old_name='cases_clien_respons_f5e6a7_idx',
        ),
        migrations.RenameIndex(
            model_name='courtfeeguide',
            new_name='cases_court_case_id_2b9836_idx',
            old_name='cases_court_case_id_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='courtfeeguide',
            new_name='cases_court_due_dat_d7fa1f_idx',
            old_name='cases_court_due_date_idx',
        ),
        migrations.RenameIndex(
            model_name='courtfeeguide',
            new_name='cases_court_payment_b42819_idx',
            old_name='cases_court_pay_status_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalsignature',
            new_name='cases_digit_user_id_46d15d_idx',
            old_name='cases_digsig_user_signed_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalsignature',
            new_name='cases_digit_signatu_cf1e37_idx',
            old_name='cases_digsig_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalsignature',
            new_name='cases_digit_documen_cac29e_idx',
            old_name='cases_digsig_document_idx',
        ),
        migrations.RenameIndex(
            model_name='electronicprotocol',
            new_name='cases_elect_case_id_3db5ad_idx',
            old_name='cases_elect_case_id_idx',
        ),
        migrations.RenameIndex(
            model_name='electronicprotocol',
            new_name='cases_elect_court_s_f46516_idx',
            old_name='cases_elect_court_s_idx',
        ),
        migrations.RenameIndex(
            model_name='electronicprotocol',
            new_name='cases_elect_created_94dea0_idx',
            old_name='cases_elect_created_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcase',
            new_name='cases_legal_status_74f6ba_idx',
            old_name='cases_legal_status_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcase',
            new_name='cases_legal_especia_b34c7f_idx',
            old_name='cases_legal_especialidade_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcase',
            new_name='cases_legal_advogad_5a003c_idx',
            old_name='cases_legal_advogado_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcase',
            new_name='cases_legal_created_3b31bd_idx',
            old_name='cases_legal_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcontract',
            new_name='cases_legal_contrac_0eed6d_idx',
            old_name='cases_legal_contrac_8f1e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcontract',
            new_name='cases_legal_status_19bfbf_idx',
            old_name='cases_legal_status_c3d4e5_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcontract',
            new_name='cases_legal_client__d9ed38_idx',
            old_name='cases_legal_client_f6g7h8_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcontract',
            new_name='cases_legal_created_f38dd8_idx',
            old_name='cases_legal_created_i9j0k1_idx',
        ),
        migrations.RenameIndex(
            model_name='legaldeadline',
            new_name='cases_legal_caso_id_d4f03f_idx',
            old_name='cases_deadline_caso_status_idx',
        ),
        migrations.RenameIndex(
            model_name='legaldeadline',
            new_name='cases_legal_data_pr_b8cf7e_idx',
            old_name='cases_deadline_data_idx',
        ),
        migrations.RenameIndex(
            model_name='legaldeadline',
            new_name='cases_legal_respons_f97cb5_idx',
            old_name='cases_deadline_responsavel_idx',
        ),
        migrations.RenameIndex(
            model_name='legalnotification',
            new_name='cases_legal_caso_id_833fff_idx',
            old_name='cases_legal_caso_id_notif_status_idx',
        ),
        migrations.RenameIndex(
            model_name='legalnotification',
            new_name='cases_legal_tipo_7e4ba3_idx',
            old_name='cases_legal_tipo_notif_idx',
        ),
        migrations.RenameIndex(
            model_name='legalnotification',
            new_name='cases_legal_prazo_v_fe64d7_idx',
            old_name='cases_legal_prazo_venc_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacaofinanceira',
            new_name='cases_movim_caso_id_0b1aed_idx',
            old_name='cases_movim_caso_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacaofinanceira',
            new_name='cases_movim_data_ve_014c49_idx',
            old_name='cases_movim_data_ve_idx',
        ),
        migrations.RenameIndex(
            model_name='oabfeetable',
            new_name='cases_oabfe_state_743c87_idx',
            old_name='cases_oabfe_state_6a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='oabfeetable',
            new_name='cases_oabfe_year_fcaca0_idx',
            old_name='cases_oabfe_year_3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='tribunalpushconfig',
            new_name='cases_tribu_user_id_85de50_idx',
            old_name='cases_tribp_user_co_idx',
        ),
        migrations.RenameIndex(
            model_name='tribunalpushconfig',
            new_name='cases_tribu_is_acti_8b809a_idx',
            old_name='cases_tribp_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tribunalpushevent',
            new_name='cases_tribu_config__225e66_idx',
            old_name='cases_tribe_config_idx',
        ),
        migrations.RenameIndex(
            model_name='tribunalpushevent',
            new_name='cases_tribu_event_t_32b130_idx',
            old_name='cases_tribe_evtype_idx',
        ),
        migrations.RenameIndex(
            model_name='tribunalpushevent',
            new_name='cases_tribu_event_d_2bd8f8_idx',
            old_name='cases_tribe_evdate_idx',
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='linked_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_documents', to='intelligent_assistant.generateddocument', verbose_name='Documento Gerado (FK)'),
        ),
        migrations.AlterField(
            model_name='casephase',
            name='reopened_reason',
            field=models.TextField(blank=True, verbose_name='Motivo da Reabertura'),
        ),
        migrations.AddField(
            model_name='invoicenfse',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='cases.legalcase'),
        ),
        migrations.AddField(
            model_name='invoicenfse',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='cases.client'),
        ),
        migrations.AddField(
            model_name='invoicenfse',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='cases.legalcontract'),
        ),
        migrations.AddField(
            model_name='invoicenfse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyerscore',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origin', to='cases.legalcase'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origin', to='cases.client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cases.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='cases.leadstage', verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='advogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='cases.legalcase'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='cases.casetask'),
        ),
        migrations.AddIndex(
            model_name='invoicenfse',
            index=models.Index(fields=['client', 'status'], name='cases_invoi_client__32c0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicenfse',
            index=models.Index(fields=['status'], name='cases_invoi_status_bb6ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicenfse',
            index=models.Index(fields=['data_competencia'], name='cases_invoi_data_co_3b5f95_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicenfse',
            index=models.Index(fields=['numero_nfse'], name='cases_invoi_numero__f0c1be_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerscore',
            index=models.Index(fields=['lawyer', 'period_start'], name='cases_lawye_lawyer__d7f6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerscore',
            index=models.Index(fields=['total_score'], name='cases_lawye_total_s_bca86d_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerscore',
            index=models.Index(fields=['rank_position'], name='cases_lawye_rank_po_ed6404_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lawyerscore',
            unique_together={('lawyer', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage'], name='cases_lead_stage_i_2985e7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['responsible'], name='cases_lead_respons_0c65b6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['temperature'], name='cases_lead_tempera_4e5916_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='cases_lead_source_77de91_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_contact_date'], name='cases_lead_next_co_f7e8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['caso', 'advogado'], name='cases_timee_caso_id_6ba8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['advogado', 'date'], name='cases_timee_advogad_73832f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['billing_type'], name='cases_timee_billing_33fdd4_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['is_approved'], name='cases_timee_is_appr_cc73c4_idx'),
        ),
    ]
