# Generated by Django 5.0.14 on 2026-05-30 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_invoicenfse_lawyerscore_lead_leadactivity_leadstage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('very_low', 'Muito Baixo'), ('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('very_high', 'Muito Alto'), ('critical', 'Crítico')], max_length=10, verbose_name='Nível de Risco')),
                ('risk_score', models.IntegerField(default=50, verbose_name='Score de Risco (0-100)')),
                ('factors', models.JSONField(blank=True, default=list, help_text='Lista de fatores: [{name, weight, description}]', verbose_name='Fatores de Risco')),
                ('analysis', models.TextField(verbose_name='Análise Detalhada')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recomendações')),
                ('trigger', models.CharField(blank=True, help_text='O que motivou esta avaliação (nova_fase, prazo_perdido, manual, etc.)', max_length=50, verbose_name='Gatilho da Avaliação')),
                ('previous_level', models.CharField(blank=True, choices=[('very_low', 'Muito Baixo'), ('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('very_high', 'Muito Alto'), ('critical', 'Crítico')], max_length=10, verbose_name='Nível Anterior')),
                ('level_changed', models.BooleanField(default=False, verbose_name='Nível Mudou')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='Gerado por IA')),
                ('ai_model', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='cases.legalcase', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Avaliação de Risco',
                'verbose_name_plural': 'Avaliações de Risco',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['caso', '-created_at'], name='cases_riska_caso_id_35bd51_idx'), models.Index(fields=['risk_level'], name='cases_riska_risk_le_ee3215_idx')],
            },
        ),
    ]
