# Generated by Django 5.0.14 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_riskassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcontract',
            name='contract_type',
            field=models.CharField(
                choices=[
                    ('honorarios', 'Contrato de Honorários'),
                    ('procuracao', 'Procuração'),
                    ('substabelecimento', 'Substabelecimento'),
                    ('prestacao_servicos', 'Contrato de Prestação de Serviços Jurídicos'),
                    ('consultoria', 'Contrato de Consultoria Jurídica'),
                    ('confidencialidade', 'Acordo de Confidencialidade / NDA'),
                    ('parceria', 'Contrato de Parceria'),
                    ('cessao_credito', 'Contrato de Cessão de Crédito'),
                    ('acordo_extrajudicial', 'Acordo Extrajudicial'),
                    ('distrato', 'Distrato / Rescisão Contratual'),
                    ('compromisso_arbitragem', 'Compromisso Arbitral'),
                    ('acordo_acionistas', 'Acordo de Acionistas'),
                    ('contrato_social', 'Contrato Social'),
                    ('termos_uso', 'Termos de Uso'),
                    ('contrato_locacao', 'Contrato de Locação'),
                    ('compra_venda', 'Contrato de Compra e Venda'),
                    ('contrato_trabalho', 'Contrato de Trabalho'),
                ],
                max_length=30,
                verbose_name='Tipo de Contrato',
            ),
        ),
    ]
