# Generated by Django 5.0.1 on 2025-10-09 02:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo do prompt",
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("corretor", "Corretor de Texto"),
                            ("exemplo", "Gerador de Exemplos"),
                            ("analise", "Análise de Qualidade"),
                            ("sugestao", "Sugestões de Melhoria"),
                            ("expansao", "Expansão de Conteúdo"),
                            ("simplificacao", "Simplificação de Texto"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Agente",
                    ),
                ),
                (
                    "field_id",
                    models.CharField(
                        blank=True,
                        help_text="Deixe em branco para prompt global",
                        max_length=255,
                        null=True,
                        verbose_name="ID do Campo",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Instruções do sistema para o agente",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Template com {{placeholders}} para variáveis",
                        verbose_name="User Prompt Template",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        default="openai",
                        max_length=20,
                        verbose_name="Provedor LLM",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Ex: gpt-4o-mini, claude-3-5-sonnet-20241022",
                        max_length=100,
                        verbose_name="Nome do Modelo",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="0.0 = mais determinístico, 2.0 = mais criativo",
                        verbose_name="Temperature",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=500, verbose_name="Max Tokens"),
                ),
                (
                    "use_rag",
                    models.BooleanField(
                        default=False,
                        help_text="Buscar contexto na Knowledge Base",
                        verbose_name="Usar RAG",
                    ),
                ),
                (
                    "rag_query_template",
                    models.TextField(
                        blank=True,
                        help_text="Template para busca no RAG. Ex: {{user_input}}",
                        verbose_name="Template de Query RAG",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Prompt padrão para este tipo de agente",
                        verbose_name="Prompt Padrão",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agent_prompts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt de Agente",
                "verbose_name_plural": "Prompts de Agentes",
                "ordering": ["agent_type", "field_id"],
                "unique_together": {("agent_type", "field_id")},
            },
        ),
    ]
