# Generated by Django 5.0.1 on 2025-10-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agentprompt",
            unique_together=set(),
        ),
    ]
