# Generated by Django 5.0.1 on 2025-10-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_agentprompt_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprompt",
            name="agent_type",
            field=models.CharField(
                help_text="Tipo livre do agente (ex: corretor, exemplo, tradutor, etc)",
                max_length=50,
                verbose_name="Tipo de Agente",
            ),
        ),
    ]
