# Generated by Django 5.0.1 on 2025-10-15 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_remove_agent_type_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_conversations", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("avg_messages_per_conversation", models.FloatField(default=0)),
                ("avg_response_time_ms", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("total_kb_queries", models.IntegerField(default=0)),
                ("total_feedbacks", models.IntegerField(default=0)),
                ("positive_feedbacks", models.IntegerField(default=0)),
                ("negative_feedbacks", models.IntegerField(default=0)),
                (
                    "satisfaction_rate",
                    models.FloatField(default=0, help_text="% de feedbacks positivos"),
                ),
                ("incorrect_count", models.IntegerField(default=0)),
                ("incomplete_count", models.IntegerField(default=0)),
                ("irrelevant_count", models.IntegerField(default=0)),
                ("unclear_count", models.IntegerField(default=0)),
                ("outdated_count", models.IntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assistant_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterField(
            model_name="agentprompt",
            name="agent_type",
            field=models.CharField(
                help_text="Tipo livre do agente (ex: corretor, exemplo, tradutor, resumo, sugestão, expansão, análise etc)",
                max_length=50,
                verbose_name="Tipo de Agente",
            ),
        ),
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID da sessão do navegador",
                        max_length=255,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_id",
                    models.UUIDField(
                        blank=True, help_text="ID do documento sendo editado", null=True
                    ),
                ),
                (
                    "current_field",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                ("total_messages", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                (
                    "avg_response_time_ms",
                    models.IntegerField(
                        default=0, help_text="Tempo médio de resposta em ms"
                    ),
                ),
                (
                    "user_satisfaction_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score 0-1 baseado em feedbacks",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assistant_conversations",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Usuário"),
                            ("assistant", "Assistente"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "llm_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(default=0)),
                (
                    "used_kb",
                    models.BooleanField(
                        default=False, help_text="Se consultou Base de Conhecimento"
                    ),
                ),
                (
                    "kb_documents_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de IDs de documentos da KB usados",
                    ),
                ),
                (
                    "kb_relevance_scores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Scores de relevância dos documentos",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agents.assistantconversation",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantKnowledgeQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField()),
                (
                    "query_embedding",
                    models.JSONField(help_text="Embedding da query (opcional)"),
                ),
                ("results_count", models.IntegerField(default=0)),
                (
                    "top_results",
                    models.JSONField(
                        default=list, help_text="Top 5 documentos retornados com scores"
                    ),
                ),
                ("query_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_queries",
                        to="agents.assistantmessage",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_kb_queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positivo (👍)"),
                            ("negative", "Negativo (👎)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("incorrect", "Informação incorreta"),
                            ("incomplete", "Resposta incompleta"),
                            ("irrelevant", "Não respondeu a pergunta"),
                            ("unclear", "Resposta confusa"),
                            ("outdated", "Informação desatualizada"),
                            ("formatting", "Formatação ruim"),
                            ("other", "Outro"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "suggested_response",
                    models.TextField(
                        blank=True,
                        help_text="Resposta sugerida pelo usuário (para fine-tuning)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Se o feedback foi processado para treino",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="agents.assistantmessage",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(
                fields=["user", "-started_at"], name="assistant_c_user_id_432cac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(
                fields=["session_id"], name="assistant_c_session_f5dc62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assistantmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="assistant_m_convers_8330f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantknowledgequery",
            index=models.Index(
                fields=["message", "-created_at"], name="assistant_k_message_1fb5a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assistantfeedback",
            index=models.Index(
                fields=["feedback_type", "-created_at"],
                name="assistant_f_feedbac_d4f1a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantfeedback",
            index=models.Index(
                fields=["processed", "-created_at"],
                name="assistant_f_process_abd8ae_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assistantfeedback",
            unique_together={("message", "user")},
        ),
    ]
