# Generated by Django 5.0.1 on 2025-10-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_assistantanalytics_alter_agentprompt_agent_type_and_more"),
        ("kb", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprompt",
            name="knowledge_bases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documentos da KB que este agente pode acessar (usado principalmente para chat_assistant)",
                related_name="agent_prompts",
                to="kb.document",
                verbose_name="Bases de Conhecimento",
            ),
        ),
    ]
