# Generated by Django 5.0.1 on 2025-10-15 03:11

from django.db import migrations


def create_default_chat_assistant(apps, schema_editor):
    """Cria assistente de chat padrão com o prompt que estava hardcoded"""
    AgentPrompt = apps.get_model('agents', 'AgentPrompt')

    # Verificar se já existe assistente de chat padrão
    if AgentPrompt.objects.filter(agent_type='chat_assistant', is_default=True).exists():
        print("⚠️ Assistente de chat padrão já existe, pulando criação...")
        return

    system_prompt = """Você é um assistente especializado em licitações e documentos governamentais brasileiros.
Seu papel é ajudar usuários a preencher formulários de ETP, Termo de Referência, e outros documentos licitatórios.

Você deve:
- Responder de forma clara e objetiva
- Citar leis e normas quando relevante (Lei 14.133/2021, IN SEGES, etc)
- Fornecer exemplos práticos quando solicitado
- Esclarecer dúvidas sobre preenchimento de campos
- Ser educado e profissional
- Quando houver informações da Base de Conhecimento, SEMPRE mencione que você está usando essas fontes
- Se a Base de Conhecimento não tiver informações relevantes, seja honesto e diga que não tem informações específicas

IMPORTANTE - FORMATO DA RESPOSTA:
- Use Markdown para formatação
- Use **negrito** para ênfase
- Use listas quando apropriado
- Use quebras de linha quando necessário

Contexto do usuário:
- Tipo de documento: {{document_type}}
- Campo atual: {{current_field}}

{{kb_context}}
"""

    user_prompt_template = "{{message}}"

    # Criar assistente padrão
    assistant = AgentPrompt.objects.create(
        name='Assistente de Licitações (Padrão)',
        description='Assistente padrão especializado em licitações e documentos governamentais brasileiros. Auxilia no preenchimento de formulários de ETP, Termo de Referência e outros documentos.',
        agent_type='chat_assistant',
        field_id=None,  # Assistentes de chat não têm field_id
        system_prompt=system_prompt,
        user_prompt_template=user_prompt_template,
        llm_provider='openai',
        model_name='gpt-4o-mini',
        temperature=0.7,
        max_tokens=1000,
        use_rag=False,  # KB é consultada dinamicamente no endpoint
        rag_query_template='',
        is_active=True,
        is_default=True,
        created_by=None  # Sistema
    )

    print(f"✅ Assistente de chat padrão criado: {assistant.id}")


def reverse_migration(apps, schema_editor):
    """Remove assistente de chat padrão criado por esta migration"""
    AgentPrompt = apps.get_model('agents', 'AgentPrompt')
    AgentPrompt.objects.filter(
        agent_type='chat_assistant',
        name='Assistente de Licitações (Padrão)'
    ).delete()
    print("🗑️ Assistente de chat padrão removido")


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_agentprompt_knowledge_bases"),
    ]

    operations = [
        migrations.RunPython(create_default_chat_assistant, reverse_migration)
    ]
