# Generated by Django 5.0.1 on 2025-10-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_create_default_chat_assistant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAssistantProxy",
            fields=[],
            options={
                "verbose_name": "Assistente de Chat",
                "verbose_name_plural": "Assistentes de Chat",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("agents.agentprompt",),
        ),
    ]
