# Generated by Django 5.0.1 on 2025-10-21 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_chatassistantproxy"),
        ("kb", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentprompt",
            options={
                "ordering": ["category", "display_order", "agent_type"],
                "verbose_name": "Agente de IA",
                "verbose_name_plural": "Agentes de IA",
            },
        ),
        migrations.AddField(
            model_name="agentprompt",
            name="category",
            field=models.CharField(
                choices=[
                    ("form_assistant", "Assistente de Formulário"),
                    ("chat_assistant", "Assistente Pessoal/Chat"),
                    ("document_generator", "Gerador de Documento"),
                ],
                default="form_assistant",
                help_text="Categoria principal do agente",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="agentprompt",
            name="color",
            field=models.CharField(
                default="#003366",
                help_text="Cor em hexadecimal para identificação visual",
                max_length=7,
                verbose_name="Cor",
            ),
        ),
        migrations.AddField(
            model_name="agentprompt",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Ordem de exibição na lista (menor = primeiro)",
                verbose_name="Ordem de Exibição",
            ),
        ),
        migrations.AddField(
            model_name="agentprompt",
            name="icon",
            field=models.CharField(
                blank=True,
                default="robot",
                help_text="Nome do ícone para exibição (ex: translate, edit, file-text)",
                max_length=50,
                verbose_name="Ícone",
            ),
        ),
        migrations.AlterField(
            model_name="agentprompt",
            name="agent_type",
            field=models.CharField(
                help_text="Subtipo específico (ex: tradutor, corretor, etp, parecer_tecnico)",
                max_length=50,
                verbose_name="Tipo/Subtipo",
            ),
        ),
        migrations.AddIndex(
            model_name="agentprompt",
            index=models.Index(
                fields=["category", "is_active"], name="agents_agen_categor_36eef1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentprompt",
            index=models.Index(
                fields=["agent_type", "field_id"], name="agents_agen_agent_t_803063_idx"
            ),
        ),
    ]
