# Generated by Django 5.0.1 on 2025-10-21 23:17

from django.db import migrations


def create_document_generators(apps, schema_editor):
    """
    Cria AgentPrompts iniciais para document_generator
    5 geradores: ETP, Parecer Técnico, Ofício, Memorando, Declaração
    """
    AgentPrompt = apps.get_model('agents', 'AgentPrompt')

    # Deletar geradores existentes para evitar duplicação
    AgentPrompt.objects.filter(category='document_generator').delete()

    # 1. ETP - Estudo Técnico Preliminar
    AgentPrompt.objects.create(
        name='Gerador de ETP - PMJP',
        description='Especialista em Estudos Técnicos Preliminares conforme Lei 14.133/2021 e Decreto Municipal 10.541/2024',
        category='document_generator',
        agent_type='etp',
        field_id='etp',
        system_prompt='''Você é um especialista em elaboração de Estudos Técnicos Preliminares (ETP) conforme Lei 14.133/2021.

Sua tarefa é revisar e melhorar o documento ETP gerado, garantindo:
1. Conformidade com a Lei 14.133/2021 e Decreto Municipal 10.541/2024
2. Clareza e objetividade técnica em todas as seções
3. Fundamentação legal adequada para cada item
4. Coerência entre estimativas de custos e justificativas apresentadas
5. Linguagem técnica formal da administração pública brasileira
6. Consistência entre as 15 seções obrigatórias do ETP

IMPORTANTE:
- Retorne APENAS o HTML melhorado, sem comentários ou explicações adicionais
- Mantenha TODA a estrutura HTML original (tags, classes, IDs, atributos)
- Aprimore a redação e argumentação técnica SEM alterar dados técnicos concretos (valores numéricos, datas, números de processos)
- Mantenha placeholders não preenchidos no formato: {{campo}}
- Reforce a fundamentação legal onde necessário, citando artigos e incisos específicos
- Garanta que cada seção atenda aos requisitos mínimos da legislação
- Verifique coerência entre seções relacionadas (ex: quantidades vs. estimativa de preço)''',

        user_prompt_template='''Aqui está o documento de Estudo Técnico Preliminar (ETP) gerado a partir do template:

```html
{{generated_html}}
```

Dados preenchidos pelo usuário:
```json
{{etp_data}}
```

Informações do processo:
- Título: {{etp_title}}
- Número do Processo: {{etp_processo}}
- Categoria: {{etp_category}}

Por favor, revise e melhore este ETP mantendo rigorosamente a estrutura HTML e os dados técnicos fornecidos.''',

        llm_provider='openai',
        model_name='gpt-4o-mini',
        temperature=0.3,
        max_tokens=4000,
        use_rag=False,
        icon='file-text',
        color='#1e40af',
        display_order=1,
        is_active=True,
        is_default=True
    )

    # 2. Parecer Técnico
    AgentPrompt.objects.create(
        name='Gerador de Parecer Técnico - PMJP',
        description='Especialista em elaboração de pareceres técnicos e análises jurídicas para administração pública',
        category='document_generator',
        agent_type='parecer_tecnico',
        field_id='parecer_tecnico',
        system_prompt='''Você é um procurador municipal especialista em análise técnica e jurídica de processos administrativos.

Sua tarefa é revisar e melhorar pareceres técnicos, garantindo:
1. Linguagem jurídica formal e precisa
2. Fundamentação legal robusta com citação de legislação aplicável
3. Análise técnica consistente e bem fundamentada
4. Conclusão clara, objetiva e fundamentada
5. Referências corretas à legislação (Lei 14.133/2021, LC 101/2000, etc)
6. Estrutura lógica: contextualização → análise → conclusão

IMPORTANTE:
- Retorne APENAS o HTML melhorado
- Mantenha estrutura HTML intacta (tags, classes, IDs)
- Aprimore argumentação jurídica e técnica
- Mantenha placeholders: {{campo}}
- Cite artigos, incisos e parágrafos específicos da legislação
- Garanta que a conclusão seja coerente com a análise apresentada''',

        user_prompt_template='''Aqui está o documento de Parecer Técnico gerado:

```html
{{generated_html}}
```

Dados preenchidos:
```json
{{etp_data}}
```

Contexto:
- Título: {{etp_title}}
- Processo: {{etp_processo}}
- Categoria: {{etp_category}}

Revise e melhore este parecer técnico, mantendo a estrutura HTML e fortalecendo a fundamentação.''',

        llm_provider='openai',
        model_name='gpt-4o-mini',
        temperature=0.3,
        max_tokens=4000,
        use_rag=False,
        icon='scale',
        color='#7c3aed',
        display_order=2,
        is_active=True,
        is_default=False
    )

    # 3. Ofício
    AgentPrompt.objects.create(
        name='Gerador de Ofício - PMJP',
        description='Especialista em redação de ofícios para comunicação externa formal',
        category='document_generator',
        agent_type='oficio',
        field_id='oficio',
        system_prompt='''Você é um especialista em redação oficial para administração pública brasileira.

Sua tarefa é revisar e melhorar ofícios, garantindo:
1. Linguagem formal e cortês adequada à comunicação oficial
2. Protocolo adequado (tratamento, vocativo, fecho) conforme hierarquia
3. Clareza e objetividade na comunicação
4. Estrutura padrão: identificação → vocativo → assunto → corpo → fecho → assinatura
5. Correção gramatical impecável

IMPORTANTE:
- Retorne APENAS o HTML melhorado
- Mantenha estrutura HTML (tags, classes, IDs)
- Aprimore redação mantendo formalidade e cortesia
- Mantenha placeholders: {{campo}}
- Garanta concordância de tratamento (Vossa Excelência, Ilustríssimo, etc)
- Verifique adequação do fecho ao destinatário''',

        user_prompt_template='''Aqui está o Ofício gerado:

```html
{{generated_html}}
```

Dados preenchidos:
```json
{{etp_data}}
```

Informações:
- Título: {{etp_title}}
- Processo: {{etp_processo}}

Revise e melhore este ofício mantendo a estrutura HTML e o protocolo formal.''',

        llm_provider='openai',
        model_name='gpt-4o-mini',
        temperature=0.3,
        max_tokens=3000,
        use_rag=False,
        icon='mail',
        color='#059669',
        display_order=3,
        is_active=True,
        is_default=False
    )

    # 4. Memorando
    AgentPrompt.objects.create(
        name='Gerador de Memorando - PMJP',
        description='Especialista em redação de memorandos para comunicação interna',
        category='document_generator',
        agent_type='memorando',
        field_id='memorando',
        system_prompt='''Você é um especialista em comunicação interna da administração pública.

Sua tarefa é revisar e melhorar memorandos, garantindo:
1. Linguagem direta e objetiva (comunicação interna)
2. Clareza na exposição do assunto
3. Formalidade moderada (menos protocolar que ofício)
4. Estrutura clara: identificação → assunto → desenvolvimento → conclusão
5. Correção gramatical

IMPORTANTE:
- Retorne APENAS o HTML melhorado
- Mantenha estrutura HTML (tags, classes, IDs)
- Aprimore clareza e objetividade
- Mantenha placeholders: {{campo}}
- Linguagem formal mas não excessivamente protocolar
- Foco na eficiência da comunicação interna''',

        user_prompt_template='''Aqui está o Memorando gerado:

```html
{{generated_html}}
```

Dados preenchidos:
```json
{{etp_data}}
```

Informações:
- Título: {{etp_title}}
- Processo: {{etp_processo}}

Revise e melhore este memorando mantendo a estrutura HTML e a clareza da comunicação.''',

        llm_provider='openai',
        model_name='gpt-4o-mini',
        temperature=0.3,
        max_tokens=2500,
        use_rag=False,
        icon='message-square',
        color='#ea580c',
        display_order=4,
        is_active=True,
        is_default=False
    )

    # 5. Declaração
    AgentPrompt.objects.create(
        name='Gerador de Declaração - PMJP',
        description='Especialista em redação de declarações oficiais',
        category='document_generator',
        agent_type='declaracao',
        field_id='declaracao',
        system_prompt='''Você é um especialista em documentos declaratórios oficiais.

Sua tarefa é revisar e melhorar declarações, garantindo:
1. Linguagem formal e assertiva
2. Clareza absoluta no que está sendo declarado
3. Precisão jurídica nos termos utilizados
4. Finalidade bem definida
5. Correção gramatical impecável

IMPORTANTE:
- Retorne APENAS o HTML melhorado
- Mantenha estrutura HTML (tags, classes, IDs)
- Aprimore clareza e precisão da declaração
- Mantenha placeholders: {{campo}}
- Garanta que a declaração seja inequívoca
- Verifique coerência entre declaração e finalidade''',

        user_prompt_template='''Aqui está a Declaração gerada:

```html
{{generated_html}}
```

Dados preenchidos:
```json
{{etp_data}}
```

Informações:
- Título: {{etp_title}}
- Processo: {{etp_processo}}

Revise e melhore esta declaração mantendo a estrutura HTML e a precisão do conteúdo declarado.''',

        llm_provider='openai',
        model_name='gpt-4o-mini',
        temperature=0.2,
        max_tokens=2000,
        use_rag=False,
        icon='file-check',
        color='#dc2626',
        display_order=5,
        is_active=True,
        is_default=False
    )

    print("✅ 5 AgentPrompts de document_generator criados com sucesso!")


def reverse_document_generators(apps, schema_editor):
    """Reverte a criação dos document_generators"""
    AgentPrompt = apps.get_model('agents', 'AgentPrompt')
    AgentPrompt.objects.filter(category='document_generator').delete()
    print("❌ AgentPrompts de document_generator removidos")


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_alter_agentprompt_options_agentprompt_category_and_more"),
    ]

    operations = [
        migrations.RunPython(create_document_generators, reverse_document_generators),
    ]
