# Generated by Django 5.0.1 on 2025-10-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_populate_document_generators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantanalytics",
            name="satisfaction_rate",
            field=models.FloatField(
                blank=True,
                help_text="% de feedbacks positivos (null se não houver feedbacks)",
                null=True,
            ),
        ),
    ]
