# Generated by Django 5.0.1 on 2025-11-04 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0010_alter_assistantanalytics_satisfaction_rate"),
        ("kb", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentprompt",
            options={
                "ordering": ["display_order", "agent_type"],
                "verbose_name": "Agente de Chat",
                "verbose_name_plural": "Agentes de Chat",
            },
        ),
        migrations.RemoveIndex(
            model_name="agentprompt",
            name="agents_agen_agent_t_803063_idx",
        ),
        migrations.RemoveField(
            model_name="agentprompt",
            name="field_id",
        ),
        migrations.AlterField(
            model_name="agentprompt",
            name="agent_type",
            field=models.CharField(
                help_text="Subtipo específico do chat (ex: especialista_licitacoes, consultor_juridico, analista_tecnico)",
                max_length=50,
                verbose_name="Tipo/Subtipo",
            ),
        ),
        migrations.AlterField(
            model_name="agentprompt",
            name="category",
            field=models.CharField(
                choices=[("chat_assistant", "Assistente Pessoal/Chat")],
                default="chat_assistant",
                help_text="Agente conversacional/chat",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
        migrations.AddIndex(
            model_name="agentprompt",
            index=models.Index(
                fields=["agent_type", "is_active"],
                name="agents_agen_agent_t_7bfea3_idx",
            ),
        ),
    ]
