# Generated by Django 5.0.1 on 2025-11-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_alter_agentprompt_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agentprompt",
            name="agents_agen_categor_36eef1_idx",
        ),
        migrations.RemoveField(
            model_name="agentprompt",
            name="category",
        ),
    ]
