# Generated by Django 5.2.11 on 2026-05-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_remove_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprompt',
            name='agent_type',
            field=models.CharField(help_text='Subtipo específico do chat (ex: advogado_civil, advogado_criminal, analista_juridico)', max_length=50, verbose_name='Tipo/Subtipo'),
        ),
    ]
