# Generated by Django 5.0.1 on 2026-01-08 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, help_text="Email no momento da acao", max_length=254
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        blank=True, help_text="Role no momento da acao", max_length=50
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Criacao"),
                            ("read", "Leitura"),
                            ("update", "Atualizacao"),
                            ("delete", "Exclusao"),
                            ("submit", "Submissao"),
                            ("approve", "Aprovacao"),
                            ("reject", "Rejeicao"),
                            ("publish", "Publicacao"),
                            ("archive", "Arquivamento"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Falha de Login"),
                            ("password_change", "Alteracao de Senha"),
                            ("generate", "Geracao"),
                            ("download", "Download"),
                            ("print", "Impressao"),
                            ("sign", "Assinatura"),
                            ("config_change", "Alteracao de Configuracao"),
                            ("permission_change", "Alteracao de Permissao"),
                            ("export", "Exportacao"),
                            ("import", "Importacao"),
                        ],
                        max_length=30,
                        verbose_name="Acao",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("warning", "Aviso"),
                            ("error", "Erro"),
                            ("critical", "Critico"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Severidade",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Ex: Document, User, Blueprint",
                        max_length=100,
                        verbose_name="Tipo de Entidade",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="ID da entidade",
                        max_length=100,
                        verbose_name="ID da Entidade",
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome/titulo para exibicao",
                        max_length=255,
                        verbose_name="Nome da Entidade",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descricao legivel da acao", verbose_name="Descricao"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="Valores anteriores",
                        null=True,
                        verbose_name="Valores Anteriores",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="Novos valores",
                        null=True,
                        verbose_name="Novos Valores",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados adicionais",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereco IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        help_text="ID para correlacao de requests",
                        max_length=100,
                        verbose_name="Request ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_auditl_created_1a76fa_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_auditl_user_id_969660_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="core_auditl_entity__244637_idx",
                    ),
                    models.Index(
                        fields=["action"], name="core_auditl_action_d9fb24_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="core_auditl_severit_6be3f0_idx"
                    ),
                ],
            },
        ),
    ]
