# Generated by Django 5.0.1 on 2026-01-09 02:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador único (ex: etp, dfd, termo_referencia)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome completo (ex: Estudo Técnico Preliminar)",
                        max_length=150,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Abreviação (ex: ETP)",
                        max_length=30,
                        verbose_name="Nome Curto",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do tipo de documento",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fase_preparatoria", "Fase Preparatória"),
                            ("fase_externa", "Fase Externa"),
                            ("impugnacoes_recursos", "Impugnações e Recursos"),
                            ("pareceres", "Pareceres"),
                            ("pos_contratacao", "Pós-Contratação"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        help_text="Fase do processo licitatório",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="FileText",
                        help_text="Nome do ícone Lucide (ex: FileText, Scale, ClipboardList)",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Cor para exibição (ex: primary, blue, green)",
                        max_length=20,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        help_text="Legislação base (ex: Lei 14.133/2021, Art. 18)",
                        max_length=255,
                        verbose_name="Base Legal",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, não aparece nas opções de seleção",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
                "ordering": ["category", "display_order", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="core_docume_code_524155_idx"),
                    models.Index(
                        fields=["category"], name="core_docume_categor_f28540_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="core_docume_is_acti_322260_idx"
                    ),
                ],
            },
        ),
    ]
