# Generated by Django 5.0.1 on 2026-01-12 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_populate_document_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador único (ex: pregao_eletronico, dispensa)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome completo (ex: Pregão Eletrônico)",
                        max_length=150,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Abreviação (ex: PE, PP, DISP)",
                        max_length=30,
                        verbose_name="Nome Curto",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do tipo de processo",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pregao", "Pregão"),
                            ("concorrencia", "Concorrência"),
                            ("dispensa", "Dispensa"),
                            ("inexigibilidade", "Inexigibilidade"),
                            ("chamamento", "Chamamento Público"),
                            ("concurso", "Concurso"),
                            ("srp", "Sistema de Registro de Preços"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        help_text="Categoria principal do tipo de processo",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        help_text="Legislação base (ex: Lei 14.133/2021, Art. 28)",
                        max_length=255,
                        verbose_name="Base Legal",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="FileText",
                        help_text="Nome do ícone Lucide",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Cor para exibição",
                        max_length=20,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, não aparece nas opções de seleção",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Processo",
                "verbose_name_plural": "Tipos de Processo",
                "ordering": ["category", "display_order", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="core_proces_code_04a54f_idx"),
                    models.Index(
                        fields=["category"], name="core_proces_categor_3d88f1_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="core_proces_is_acti_0cdef3_idx"
                    ),
                ],
            },
        ),
    ]
