# Generated by Django 5.0.1 on 2026-01-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_populate_process_statuses"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="processstatus",
            new_name="core_proces_code_249675_idx",
            old_name="core_proces_code_7a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="processstatus",
            new_name="core_proces_categor_9632f5_idx",
            old_name="core_proces_categor_8d3e4f_idx",
        ),
        migrations.RenameIndex(
            model_name="processstatus",
            new_name="core_proces_is_acti_0c9710_idx",
            old_name="core_proces_is_acti_9e5f6a_idx",
        ),
    ]
