# Generated by Django 5.0.1 on 2026-02-02 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0008_rename_core_proces_code_7a1b2c_idx_core_proces_code_249675_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Identificador único (ex: forms, documents, intelligent_assistant)",
                        max_length=50,
                        unique=True,
                        verbose_name="Chave",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome de exibição (ex: Formulários, Documentos)",
                        max_length=100,
                        verbose_name="Nome",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "icon",
                    models.CharField(
                        default="Box",
                        help_text="Nome do ícone Lucide",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "permission_codename",
                    models.CharField(
                        help_text="Codename da permissão Django (ex: can_access_forms)",
                        max_length=100,
                        unique=True,
                        verbose_name="Permissão",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="Rota no frontend (ex: /dashboard/forms)",
                        max_length=100,
                        verbose_name="Rota",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o módulo está habilitado no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Módulo do Sistema",
                "verbose_name_plural": "Módulos do Sistema",
                "ordering": ["display_order", "name"],
                "permissions": [
                    ("can_access_forms", "Pode acessar Formulários"),
                    ("can_access_documents", "Pode acessar Documentos"),
                    ("can_access_templates", "Pode acessar Templates"),
                    ("can_access_kb", "Pode acessar Base de Conhecimento"),
                    ("can_access_rag", "Pode acessar RAG"),
                    (
                        "can_access_intelligent_assistant",
                        "Pode acessar Assistente Inteligente",
                    ),
                    ("can_access_workflows", "Pode acessar Processos"),
                    ("can_access_agents", "Pode acessar Agentes"),
                ],
            },
        ),
    ]
