# Generated by Django 5.0.1 on 2026-02-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_system_module"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemmodule",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Módulo do Sistema",
                "verbose_name_plural": "Módulos do Sistema",
            },
        ),
    ]
