# Generated by Django 5.0.1 on 2026-02-18 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_systemmodule_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador único (ex: anthropic, openai, watsonx)",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome de exibição (ex: Anthropic (Claude))",
                        max_length=100,
                        verbose_name="Nome",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "api_key",
                    models.TextField(
                        blank=True,
                        help_text="Chave de autenticação da API",
                        verbose_name="API Key",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        help_text="URL base da API (obrigatório para watsonx)",
                        verbose_name="URL da API",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Ex: {"project_id": "xxx"} para watsonx',
                        verbose_name="Configurações extras",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Cpu",
                        help_text="Nome do ícone Lucide",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Cor hex para exibição",
                        max_length=20,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, não aparece nas opções de seleção",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Provedor LLM",
                "verbose_name_plural": "Provedores LLM",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="core_llmprov_code_idx"),
                    models.Index(fields=["is_active"], name="core_llmprov_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="Identificador da API (ex: claude-sonnet-4-5-20250514, gpt-4o)",
                        max_length=100,
                        verbose_name="ID do Modelo",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nome amigável (ex: Claude Sonnet 4.5, GPT-4o)",
                        max_length=100,
                        verbose_name="Nome de Exibição",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do modelo e seus pontos fortes",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "max_tokens_limit",
                    models.PositiveIntegerField(
                        default=4096,
                        help_text="Máximo de tokens de saída suportado",
                        verbose_name="Limite de Tokens",
                    ),
                ),
                (
                    "default_temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Valor padrão de temperature para este modelo",
                        verbose_name="Temperature Padrão",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, não aparece nas opções de seleção",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="core.llmprovider",
                        verbose_name="Provedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo LLM",
                "verbose_name_plural": "Modelos LLM",
                "ordering": ["provider", "display_order", "display_name"],
                "indexes": [
                    models.Index(
                        fields=["provider", "is_active"],
                        name="core_llmmodel_prov_active_idx",
                    ),
                    models.Index(fields=["model_id"], name="core_llmmodel_modelid_idx"),
                ],
                "unique_together": {("provider", "model_id")},
            },
        ),
    ]
