# Generated by Django 5.0.1 on 2026-02-18 14:47
# Data migration: popula providers e modelos LLM iniciais

from django.db import migrations


def populate_providers(apps, schema_editor):
    LLMProvider = apps.get_model('core', 'LLMProvider')
    LLMModel = apps.get_model('core', 'LLMModel')

    # ── Anthropic ──
    anthropic = LLMProvider.objects.create(
        code='anthropic',
        name='Anthropic (Claude)',
        description='Modelos Claude da Anthropic',
        icon='Brain',
        color='#D97706',
        display_order=0,
        is_active=True,
    )
    anthropic_models = [
        ('claude-sonnet-4-5-20250514', 'Claude Sonnet 4.5', 8192, 0.7, 0),
        ('claude-haiku-4-5', 'Claude Haiku 4.5', 8192, 0.7, 1),
        ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet', 8192, 0.7, 2),
        ('claude-3-opus-20240229', 'Claude 3 Opus', 4096, 0.7, 3),
        ('claude-3-haiku-20240307', 'Claude 3 Haiku', 4096, 0.7, 4),
    ]
    for model_id, name, max_tokens, temp, order in anthropic_models:
        LLMModel.objects.create(
            provider=anthropic,
            model_id=model_id,
            display_name=name,
            max_tokens_limit=max_tokens,
            default_temperature=temp,
            display_order=order,
            is_active=True,
        )

    # ── OpenAI ──
    openai = LLMProvider.objects.create(
        code='openai',
        name='OpenAI (GPT)',
        description='Modelos GPT da OpenAI',
        icon='Zap',
        color='#10A37F',
        display_order=1,
        is_active=True,
    )
    openai_models = [
        ('gpt-4o', 'GPT-4o', 4096, 0.7, 0),
        ('gpt-4o-mini', 'GPT-4o Mini', 4096, 0.7, 1),
        ('gpt-4-turbo', 'GPT-4 Turbo', 4096, 0.7, 2),
        ('gpt-3.5-turbo', 'GPT-3.5 Turbo', 4096, 0.7, 3),
    ]
    for model_id, name, max_tokens, temp, order in openai_models:
        LLMModel.objects.create(
            provider=openai,
            model_id=model_id,
            display_name=name,
            max_tokens_limit=max_tokens,
            default_temperature=temp,
            display_order=order,
            is_active=True,
        )

    # ── IBM watsonx ──
    watsonx = LLMProvider.objects.create(
        code='watsonx',
        name='IBM watsonx.ai',
        description='Modelos via IBM watsonx.ai (Granite, Llama, Mixtral)',
        icon='Cloud',
        color='#0F62FE',
        display_order=2,
        is_active=False,  # Desativado por padrão até configurar API key
    )
    watsonx_models = [
        ('ibm/granite-13b-chat-v2', 'Granite 13B Chat v2', 4096, 0.7, 0),
        ('ibm/granite-3-8b-instruct', 'Granite 3 8B Instruct', 4096, 0.7, 1),
        ('meta-llama/llama-3-1-70b-instruct', 'Llama 3.1 70B Instruct', 4096, 0.7, 2),
        ('meta-llama/llama-3-1-8b-instruct', 'Llama 3.1 8B Instruct', 4096, 0.7, 3),
        ('mistralai/mixtral-8x7b-instruct-v01', 'Mixtral 8x7B Instruct', 4096, 0.7, 4),
    ]
    for model_id, name, max_tokens, temp, order in watsonx_models:
        LLMModel.objects.create(
            provider=watsonx,
            model_id=model_id,
            display_name=name,
            max_tokens_limit=max_tokens,
            default_temperature=temp,
            display_order=order,
            is_active=True,
        )


def reverse_providers(apps, schema_editor):
    LLMProvider = apps.get_model('core', 'LLMProvider')
    LLMProvider.objects.filter(code__in=['anthropic', 'openai', 'watsonx']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_llm_provider_and_model"),
    ]

    operations = [
        migrations.RunPython(populate_providers, reverse_providers),
    ]
