# Generated by Django 5.2.11 on 2026-03-25 04:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_update_watsonx_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Identificador único (ex: edital_analysis, document_review)",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nome amigável (ex: Análise de Editais)",
                        max_length=200,
                        verbose_name="Nome de Exibição",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do que este agente faz",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Personalidade e instruções base do agente",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Template com placeholders: {{text}}, {{objeto}}, {{questions}}",
                        verbose_name="Template do User Prompt",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de perguntas que o agente deve responder. Ex: ["Objeto da contratação", "Valor estimado"]',
                        verbose_name="Perguntas",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        default="watsonx",
                        help_text="anthropic, openai, watsonx",
                        max_length=30,
                        verbose_name="Provider LLM",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="mistralai/mistral-medium-2505",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.3,
                        max_digits=3,
                        verbose_name="Temperatura",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=2048, verbose_name="Max Tokens"),
                ),
                (
                    "max_input_chars",
                    models.IntegerField(
                        default=15000,
                        help_text="Limite de caracteres do texto de entrada antes de truncar",
                        verbose_name="Max Chars Input",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Ativo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração de Análise IA",
                "verbose_name_plural": "Configurações de Análise IA",
                "ordering": ["name"],
            },
        ),
    ]
