# Generated by Django 5.2.11 on 2026-04-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_ai_analysis_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="category",
            field=models.CharField(
                choices=[
                    ("fase_preparatoria", "Fase Preparatória"),
                    ("fase_externa", "Fase Externa"),
                    ("fase_contratacao", "Fase de Contratação"),
                    ("impugnacoes_recursos", "Impugnações e Recursos"),
                    ("pareceres", "Pareceres"),
                    ("pos_contratacao", "Pós-Contratação"),
                    ("outros", "Outros"),
                ],
                default="outros",
                help_text="Fase do processo licitatório",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
    ]
