# Generated by Django 5.2.11 on 2026-05-22 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_documenttype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Identificador único (slug, ex: fase_preparatoria)', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nome de exibição (ex: Fase Preparatória)', max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição da categoria', verbose_name='Descrição')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documento',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='core_docume_code_469f5a_idx'), models.Index(fields=['is_active', 'display_order'], name='core_docume_is_acti_125e47_idx')],
            },
        ),
    ]
