# Generated by Django 5.2.11 on 2026-05-25 23:30
# Nota: RenameIndex removido manualmente — índice não existe no DB (criado em 0018 com nome diferente).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_documenttype_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='category',
            field=models.ForeignKey(help_text='Categoria do documento jurídico', on_delete=django.db.models.deletion.PROTECT, related_name='document_types', to='core.documentcategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(help_text='Identificador único (ex: peticao_inicial, contrato, parecer)', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(help_text='Nome completo (ex: Petição Inicial)', max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='short_name',
            field=models.CharField(blank=True, help_text='Abreviação (ex: PI, CTR, PAR)', max_length=30, verbose_name='Nome Curto'),
        ),
        migrations.AlterField(
            model_name='processstatus',
            name='code',
            field=models.CharField(help_text='Identificador único (ex: em_andamento, aguardando_sentenca, concluido)', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='category',
            field=models.CharField(choices=[('civel', 'Cível'), ('criminal', 'Criminal'), ('trabalhista', 'Trabalhista'), ('tributario', 'Tributário'), ('administrativo', 'Administrativo'), ('previdenciario', 'Previdenciário'), ('familia', 'Família e Sucessões'), ('empresarial', 'Empresarial'), ('outros', 'Outros')], default='outros', help_text='Categoria principal do tipo de processo', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='code',
            field=models.CharField(help_text='Identificador único (ex: acao_civil, habeas_corpus)', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='name',
            field=models.CharField(help_text='Nome completo (ex: Ação Civil Pública)', max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='short_name',
            field=models.CharField(blank=True, help_text='Abreviação (ex: ACP, HC, MS)', max_length=30, verbose_name='Nome Curto'),
        ),
    ]
