# Generated by Django 5.0.1
# Data migration: Ativa watsonx se a API key estiver configurada

from django.db import migrations


def activate_watsonx_if_configured(apps, schema_editor):
    """
    Ativa o provider watsonx e seus modelos se a API key estiver configurada.
    """
    LLMProvider = apps.get_model('core', 'LLMProvider')
    LLMModel = apps.get_model('core', 'LLMModel')

    try:
        watsonx = LLMProvider.objects.filter(code='watsonx').first()
        if watsonx:
            # Ativa o provider se tiver API key ou se estiver em ambiente de desenvolvimento
            if watsonx.api_key:
                watsonx.is_active = True
                watsonx.save(update_fields=['is_active'])
                print('watsonx.ai ativado (API key configurada)')
            else:
                # Mesmo sem API key, manter ativo para permitir configuração via admin
                watsonx.is_active = True
                watsonx.save(update_fields=['is_active'])
                print('watsonx.ai ativado (configure a API key no admin)')

            # Ativa todos os modelos watsonx
            for model in watsonx.models.all():
                model.is_active = True
                model.save(update_fields=['is_active'])

    except Exception as e:
        print(f'Erro ao ativar watsonx: {e}')


def deactivate_watsonx(apps, schema_editor):
    """Reverte: desativa watsonx."""
    LLMProvider = apps.get_model('core', 'LLMProvider')

    try:
        watsonx = LLMProvider.objects.filter(code='watsonx').first()
        if watsonx:
            watsonx.is_active = False
            watsonx.save(update_fields=['is_active'])
    except Exception as e:
        print(f'Erro ao reverter watsonx: {e}')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_core_docume_categor_f28540_idx_core_docume_categor_235f9c_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(activate_watsonx_if_configured, deactivate_watsonx),
    ]
