# Generated by Django 5.0.1

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_activate_watsonx_if_configured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_provider', models.CharField(
                    choices=[
                        ('openai', 'OpenAI'),
                        ('anthropic', 'Anthropic'),
                        ('watsonx', 'WatsonX'),
                        ('other', 'Outro'),
                    ],
                    help_text='Provedor do modelo de IA',
                    max_length=30,
                    verbose_name='Provedor',
                )),
                ('model_name', models.CharField(
                    blank=True,
                    help_text='Nome do modelo utilizado (ex: claude-sonnet-4-5-20250514)',
                    max_length=100,
                    verbose_name='Modelo',
                )),
                ('usage_type', models.CharField(
                    choices=[
                        ('copilot', 'Copilot'),
                        ('agent', 'Agente IA'),
                        ('document_gen', 'Geração de Documento'),
                        ('user_request', 'Solicitação do Usuário'),
                        ('analysis', 'Análise'),
                        ('other', 'Outro'),
                    ],
                    default='other',
                    max_length=30,
                    verbose_name='Tipo de Uso',
                )),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de Entrada')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de Saída')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Total de Tokens')),
                ('cost_estimate', models.DecimalField(
                    decimal_places=6,
                    default=0,
                    help_text='Custo estimado em dólares',
                    max_digits=10,
                    verbose_name='Custo Estimado (USD)',
                )),
                ('description', models.TextField(
                    blank=True,
                    help_text='Descrição da operação realizada',
                    verbose_name='Descrição',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='token_usage_logs',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Usuário',
                )),
            ],
            options={
                'verbose_name': 'Log de Uso de Tokens',
                'verbose_name_plural': 'Logs de Uso de Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['-created_at'], name='core_tokenu_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['user', '-created_at'], name='core_tokenu_user_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['model_provider'], name='core_tokenu_provid_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['usage_type'], name='core_tokenu_usage_idx'),
        ),
    ]
