# Generated by Django 5.0.1 on 2025-10-09 01:15

import apps.forms.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("etp", "ETP - Estudo Técnico Preliminar"),
                            ("termo_referencia", "Termo de Referência"),
                            ("projeto_basico", "Projeto Básico"),
                            ("custom", "Customizado"),
                        ],
                        default="etp",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=list,
                        validators=[apps.forms.models.validate_form_fields],
                        verbose_name="Campos",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="Versão")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_form_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Formulário",
                "verbose_name_plural": "Templates de Formulários",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="forms_formt_is_acti_fc88ff_idx",
                    )
                ],
            },
        ),
    ]
