# Generated by Django 5.0.1 on 2025-10-21 18:19

import apps.forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formtemplate",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.forms.models.validate_form_sections],
                verbose_name="Seções",
            ),
        ),
        migrations.AlterField(
            model_name="formtemplate",
            name="fields",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.forms.models.validate_form_fields],
                verbose_name="Campos",
            ),
        ),
    ]
