# Generated by Django 5.0.1 on 2025-10-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_formtemplate_sections_alter_formtemplate_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("etp", "ETP - Estudo Técnico Preliminar"),
                    ("termo_referencia", "Termo de Referência"),
                    ("projeto_basico", "Projeto Básico"),
                    ("projeto_executivo", "Projeto Executivo"),
                    ("parecer_tecnico", "Parecer Técnico"),
                    ("estudo_de_impacto", "Estudo de Impacto"),
                    ("custom", "Customizado"),
                ],
                default="etp",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
    ]
