# Generated by Django 5.0.1 on 2025-11-04 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_alter_formtemplate_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormAssistant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo do assistente",
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "assistant_type",
                    models.CharField(
                        help_text="Ex: tradutor, corretor, expansor, validador",
                        max_length=50,
                        verbose_name="Tipo de Assistente",
                    ),
                ),
                (
                    "field_id",
                    models.CharField(
                        help_text="ID do campo do formulário que este assistente auxilia",
                        max_length=255,
                        verbose_name="ID do Campo",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Instruções do sistema para o assistente",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Template com {{placeholders}} para variáveis do campo",
                        verbose_name="User Prompt Template",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        default="openai",
                        max_length=20,
                        verbose_name="Provedor LLM",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Ex: gpt-4o-mini, claude-3-5-sonnet-20241022",
                        max_length=100,
                        verbose_name="Nome do Modelo",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="0.0 = mais determinístico, 2.0 = mais criativo",
                        verbose_name="Temperature",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=500, verbose_name="Max Tokens"),
                ),
                (
                    "use_rag",
                    models.BooleanField(
                        default=False,
                        help_text="Buscar contexto na Knowledge Base",
                        verbose_name="Usar RAG",
                    ),
                ),
                (
                    "rag_query_template",
                    models.TextField(
                        blank=True,
                        help_text="Template para busca no RAG. Ex: {{field_value}}",
                        verbose_name="Template de Query RAG",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="wand-2",
                        help_text="Nome do ícone Lucide para exibição",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Cor em hexadecimal para identificação visual",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Ordem de exibição no campo (menor = primeiro)",
                        verbose_name="Ordem de Exibição",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Assistente padrão para este campo",
                        verbose_name="Assistente Padrão",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_form_assistants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistente de Formulário",
                "verbose_name_plural": "Assistentes de Formulário",
                "ordering": ["field_id", "display_order", "assistant_type"],
                "indexes": [
                    models.Index(
                        fields=["field_id", "is_active"],
                        name="forms_forma_field_i_1f5e66_idx",
                    ),
                    models.Index(
                        fields=["assistant_type"], name="forms_forma_assista_a35743_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="formassistant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("field_id", "is_default"),
                name="unique_default_assistant_per_field",
            ),
        ),
    ]
