# Generated by Django 5.0.1 on 2025-11-04 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_formassistant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formassistant",
            options={
                "ordering": ["display_order", "assistant_type"],
                "verbose_name": "Assistente de Formulário",
                "verbose_name_plural": "Assistentes de Formulário",
            },
        ),
        migrations.RemoveConstraint(
            model_name="formassistant",
            name="unique_default_assistant_per_field",
        ),
        migrations.RemoveIndex(
            model_name="formassistant",
            name="forms_forma_field_i_1f5e66_idx",
        ),
        migrations.RemoveField(
            model_name="formassistant",
            name="field_id",
        ),
        migrations.AddIndex(
            model_name="formassistant",
            index=models.Index(
                fields=["is_active"], name="forms_forma_is_acti_70ae3b_idx"
            ),
        ),
    ]
