# Generated by Django 5.0.1 on 2025-11-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0005_rename_documents_etp_user_id_6a6aaa_idx_documents_d_user_id_200c84_idx_and_more",
        ),
        ("forms", "0005_alter_formassistant_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formtemplate",
            name="deleted_generator_info",
            field=models.JSONField(
                blank=True,
                help_text="Armazena informações quando um gerador vinculado é removido",
                null=True,
                verbose_name="Info do Gerador Deletado",
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="document_generator",
            field=models.ForeignKey(
                blank=True,
                help_text="Gerador de documento que será usado ao finalizar este formulário",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_templates",
                to="documents.documentgenerator",
                verbose_name="Gerador de Documento",
            ),
        ),
    ]
