# Generated by Django 5.0.1 on 2026-02-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_formtemplate_deleted_generator_info_and_more"),
        ("intelligent_assistant", "0005_documentblueprint_blueprintsection_generationsession_and_more"),
    ]

    operations = [
        # Remover campos relacionados ao DocumentGenerator
        migrations.RemoveField(
            model_name="formtemplate",
            name="document_generator",
        ),
        migrations.RemoveField(
            model_name="formtemplate",
            name="deleted_generator_info",
        ),
        # Adicionar FK para DocumentBlueprint
        migrations.AddField(
            model_name="formtemplate",
            name="blueprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Blueprint de documento que define os agentes disponíveis para este formulário",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_templates",
                to="intelligent_assistant.documentblueprint",
                verbose_name="Blueprint",
            ),
        ),
    ]
