# Generated by Django 5.0.1 on 2025-10-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("admin", "Administrador da Organização"),
                    ("manager", "Gestor"),
                    ("analyst", "Analista"),
                    ("viewer", "Visualizador"),
                ],
                default="analyst",
                max_length=20,
                verbose_name="Perfil",
            ),
        ),
    ]
