# Generated by Django 5.0.1 on 2025-10-12 02:17

from django.db import migrations


def fix_invalid_roles(apps, schema_editor):
    """
    Corrige roles inválidos no banco de dados.
    Converte roles antigos/inválidos para roles válidos.
    """
    User = apps.get_model('accounts', 'User')

    # Mapeamento de roles inválidos para válidos
    role_mapping = {
        'user': 'analyst',  # Role genérico vira analista
        '': 'analyst',      # Role vazio vira analista
        None: 'analyst',    # Role null vira analista
    }

    # Lista de roles válidos
    valid_roles = ['superadmin', 'admin', 'manager', 'analyst', 'viewer']

    users_updated = 0
    for user in User.objects.all():
        if user.role not in valid_roles:
            old_role = user.role
            new_role = role_mapping.get(user.role, 'analyst')
            user.role = new_role
            user.save()
            users_updated += 1
            print(f"User {user.username} (ID: {user.id}): role '{old_role}' → '{new_role}'")

    if users_updated > 0:
        print(f"✓ {users_updated} usuário(s) atualizado(s)")
    else:
        print("✓ Todos os roles estão corretos")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(fix_invalid_roles, reverse_code=migrations.RunPython.noop),
    ]
