# Generated by Django 5.0.1 on 2025-10-22 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_fix_invalid_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        default="contrata.ai",
                        help_text="Nome exibido no sistema",
                        max_length=100,
                        verbose_name="Nome do Sistema",
                    ),
                ),
                (
                    "system_tagline",
                    models.CharField(
                        blank=True,
                        help_text="Descrição curta do sistema",
                        max_length=255,
                        verbose_name="Tagline",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo principal (PNG, SVG, JPG - recomendado 200x60px)",
                        null=True,
                        upload_to="brand/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True,
                        help_text="Logo para tema escuro (opcional)",
                        null=True,
                        upload_to="brand/",
                        verbose_name="Logo Dark Mode",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Ícone do navegador (.ico, .png - 32x32px ou 64x64px)",
                        null=True,
                        upload_to="brand/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Cor principal em hexadecimal (ex: #3b82f6)",
                        max_length=7,
                        verbose_name="Cor Primária",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#8b5cf6",
                        help_text="Cor secundária em hexadecimal (ex: #8b5cf6)",
                        max_length=7,
                        verbose_name="Cor Secundária",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#10b981",
                        help_text="Cor para destaques e ações (ex: #10b981)",
                        max_length=7,
                        verbose_name="Cor de Destaque",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brand_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Marca",
                "verbose_name_plural": "Configurações de Marca",
            },
        ),
    ]
