# Generated by Django 5.0.1 on 2025-10-09 01:53

import apps.templates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("etp", "ETP - Estudo Técnico Preliminar"),
                            ("termo_referencia", "Termo de Referência"),
                            ("projeto_basico", "Projeto Básico"),
                            ("custom", "Customizado"),
                        ],
                        default="etp",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("docx", "DOCX"),
                            ("markdown", "Markdown"),
                        ],
                        default="html",
                        max_length=20,
                        verbose_name="Tipo de Template",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Template com placeholders {{field_id}}. Ex: {{descricao_necessidade}}",
                        verbose_name="Conteúdo do Template",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload de arquivo .html ou .docx",
                        null=True,
                        upload_to="templates/documents/",
                        validators=[apps.templates.models.validate_template_file],
                        verbose_name="Arquivo de Template",
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        help_text="CSS para estilização do documento HTML",
                        verbose_name="CSS Customizado",
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de variáveis/placeholders disponíveis no template",
                        verbose_name="Variáveis Disponíveis",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="Versão")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Template padrão para a categoria",
                        verbose_name="Template Padrão",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_document_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "form_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Formulário associado a este template de documento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_templates",
                        to="forms.formtemplate",
                        verbose_name="Template de Formulário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Documento",
                "verbose_name_plural": "Templates de Documentos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="templates_d_categor_80d1da_idx",
                    ),
                    models.Index(
                        fields=["is_default", "category"],
                        name="templates_d_is_defa_8002c2_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("category", "is_default"),
                name="unique_default_per_category",
            ),
        ),
    ]
