# Generated by Django 5.0.1 on 2025-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("html", "HTML"),
                    ("tinymce", "TinyMCE"),
                    ("docx", "DOCX"),
                    ("markdown", "Markdown"),
                ],
                default="html",
                max_length=20,
                verbose_name="Tipo de Template",
            ),
        ),
    ]
