# Generated by Django 5.0.1 on 2025-11-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_alter_documenttemplate_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttemplate",
            name="form_template",
        ),
    ]
