# Generated by Django 5.0.1 on 2026-02-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_remove_documentgenerator_add_blueprint"),
        ("templates", "0004_remove_documenttemplate_form_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="form_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Formulário que fornece os dados para preencher este template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_templates",
                to="forms.formtemplate",
                verbose_name="Formulário Associado",
            ),
        ),
    ]
