# Generated by Django 5.0.1 on 2026-02-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0006_category_to_document_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documenttemplate",
            new_name="templates_d_documen_90cec2_idx",
            old_name="templates_do_documen_idx",
        ),
        migrations.RenameIndex(
            model_name="documenttemplate",
            new_name="templates_d_is_defa_6690cf_idx",
            old_name="templates_do_is_defa_dt_idx",
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Template padrão para o tipo de documento",
                verbose_name="Template Padrão",
            ),
        ),
    ]
