# Generated by Django 5.0.1 on 2025-10-09 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ETP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, verbose_name="Dados do Formulário"),
                ),
                (
                    "generated_content",
                    models.TextField(
                        blank=True, verbose_name="Conteúdo Gerado"),
                ),
                (
                    "generated_html",
                    models.TextField(
                        blank=True, verbose_name="HTML Gerado (TinyMCE)"),
                ),
                (
                    "exported_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF ou DOCX exportado",
                        null=True,
                        upload_to="Documents/exports/",
                        verbose_name="Arquivo Exportado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("in_review", "Em Revisão"),
                            ("completed", "Completo"),
                            ("archived", "Arquivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=500,
                                     verbose_name="Título"),
                ),
                ("description", models.TextField(
                    blank=True, verbose_name="Descrição")),
                ("version", models.IntegerField(default=1, verbose_name="Versão")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado em"
                    ),
                ),
                (
                    "document_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Documents",
                        to="templates.documenttemplate",
                        verbose_name="Template de Documento",
                    ),
                ),
                (
                    "form_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Documents",
                        to="forms.formtemplate",
                        verbose_name="Template de Formulário",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="documents.etp",
                        verbose_name="ETP Original",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "ETP",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="Documents_etp_user_id_6a6aaa_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="Documents_etp_created_f84878_idx"
                    ),
                ],
            },
        ),
    ]
