# Generated by Django 5.0.1 on 2025-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etp",
            name="numero_processo",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Número do Processo"
            ),
        ),
        migrations.AddField(
            model_name="etp",
            name="progress",
            field=models.IntegerField(
                default=0,
                help_text="Percentual de preenchimento do formulário (0-100%)",
                verbose_name="Progresso",
            ),
        ),
    ]
