# Generated by Django 5.0.1 on 2025-11-04 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_rename_etp_to_document"),
        ("kb", "0002_initial"),
        ("templates", "0003_alter_documenttemplate_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentGenerator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo do gerador",
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "document_type",
                    models.CharField(
                        help_text="Ex: etp, parecer_tecnico, oficio, memorando",
                        max_length=50,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Instruções do sistema para o gerador de documentos",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Template com {{placeholders}} para dados do formulário",
                        verbose_name="User Prompt Template",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        default="openai",
                        max_length=20,
                        verbose_name="Provedor LLM",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-4o",
                        help_text="Ex: gpt-4o, claude-3-5-sonnet-20241022",
                        max_length=100,
                        verbose_name="Nome do Modelo",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="0.0 = mais determinístico, 2.0 = mais criativo",
                        verbose_name="Temperature",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=4000, verbose_name="Max Tokens"),
                ),
                (
                    "use_rag",
                    models.BooleanField(
                        default=True,
                        help_text="Buscar contexto na Knowledge Base",
                        verbose_name="Usar RAG",
                    ),
                ),
                (
                    "rag_query_template",
                    models.TextField(
                        blank=True,
                        help_text="Template para busca no RAG. Ex: {{document_type}} {{description}}",
                        verbose_name="Template de Query RAG",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="file-text",
                        help_text="Nome do ícone Lucide para exibição",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10b981",
                        help_text="Cor em hexadecimal para identificação visual",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Ordem de exibição na lista (menor = primeiro)",
                        verbose_name="Ordem de Exibição",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Gerador padrão para este tipo de documento",
                        verbose_name="Gerador Padrão",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Gerador de Documento",
                "verbose_name_plural": "Geradores de Documento",
                "ordering": ["document_type", "display_order"],
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="documents.document",
                verbose_name="Documento Original",
            ),
        ),
        migrations.AddField(
            model_name="documentgenerator",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_document_generators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="documentgenerator",
            name="document_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template que este gerador usa como base",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generators",
                to="templates.documenttemplate",
                verbose_name="Template de Documento",
            ),
        ),
        migrations.AddField(
            model_name="documentgenerator",
            name="knowledge_bases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documentos da KB que este gerador pode acessar",
                related_name="document_generators",
                to="kb.document",
                verbose_name="Bases de Conhecimento",
            ),
        ),
        migrations.AddIndex(
            model_name="documentgenerator",
            index=models.Index(
                fields=["document_type", "is_active"],
                name="documents_d_documen_24209b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentgenerator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("document_type", "is_default"),
                name="unique_default_generator_per_doc_type",
            ),
        ),
    ]
