# Generated by Django 5.0.1 on 2025-11-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documentgenerator_alter_document_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_user_id_200c84_idx",
            old_name="Documents_etp_user_id_6a6aaa_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_created_71dced_idx",
            old_name="Documents_etp_created_f84878_idx",
        ),
    ]
