# Generated by Django 5.0.1 on 2026-01-08 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0005_rename_documents_etp_user_id_6a6aaa_idx_documents_d_user_id_200c84_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_generator",
            field=models.ForeignKey(
                blank=True,
                help_text="Gerador usado para criar este documento (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_documents",
                to="documents.documentgenerator",
                verbose_name="Gerador de Documento",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Preenchimento Manual"),
                    ("generator", "Gerador de Documento"),
                    ("assistant", "Assistente Inteligente"),
                ],
                default="manual",
                help_text="Como o documento foi criado",
                max_length=20,
                verbose_name="Origem",
            ),
        ),
    ]
