# Generated by Django 5.0.1 on 2026-02-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_add_source_and_generator_fields"),
        ("forms", "0007_remove_documentgenerator_add_blueprint"),
    ]

    operations = [
        # Remover FK document_generator de Document
        migrations.RemoveField(
            model_name="document",
            name="document_generator",
        ),
        # Deletar model DocumentGenerator
        migrations.DeleteModel(
            name="DocumentGenerator",
        ),
    ]
