# Generated by Django 5.2.11 on 2026-03-17 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CopilotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Copilot contrata.ai",
                        help_text="Nome exibido na interface do Copilot.",
                        max_length=100,
                        verbose_name="Nome do assistente",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text='Instruções de comportamento do assistente. Use linguagem direta: "Você é...", "Você deve...", "NÃO faça...". O contexto de KB é injetado automaticamente após este prompt.',
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("watsonx", "IBM watsonx (Llama)"),
                            ("anthropic", "Anthropic (Claude)"),
                            ("openai", "OpenAI (GPT)"),
                        ],
                        default="watsonx",
                        help_text="Provedor de IA. As credenciais são gerenciadas em Core › Provedores LLM.",
                        max_length=20,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="meta-llama/llama-3-3-70b-instruct",
                        help_text="Exemplos: meta-llama/llama-3-3-70b-instruct, claude-sonnet-4-6, gpt-4o.",
                        max_length=100,
                        verbose_name="ID do modelo",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Criatividade das respostas. 0 = determinístico, 1 = mais criativo. Recomendado: 0.5–0.8.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Temperatura",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=4096,
                        help_text="Limite de tokens gerados por resposta. Padrão: 4096.",
                        validators=[
                            django.core.validators.MinValueValidator(256),
                            django.core.validators.MaxValueValidator(16384),
                        ],
                        verbose_name="Máx. tokens de saída",
                    ),
                ),
                (
                    "max_kb_results",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Quantidade de chunks buscados na Base de Conhecimento por mensagem. Padrão: 10.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Resultados da KB",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se desativado, o Copilot retorna erro ao tentar conversar.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Copilot",
                "verbose_name_plural": "Configuração do Copilot",
            },
        ),
    ]
