# Generated by Django 5.0.1 on 2025-10-09 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("kb", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Contexto"),
                ),
                ("description", models.TextField(
                    blank=True, verbose_name="Descrição")),
                (
                    "default_top_k",
                    models.IntegerField(
                        default=5, verbose_name="Top K Padrão"),
                ),
                (
                    "default_threshold",
                    models.FloatField(
                        default=0.7, verbose_name="Threshold Padrão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rag_contexts",
                        to="kb.document",
                        verbose_name="Documentos",
                    ),
                ),
                (
                    "etp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_contexts",
                        to="documents.document",
                        verbose_name="Documento Relacionado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_contexts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contexto RAG",
                "verbose_name_plural": "Contextos RAG",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="rag_ragcont_user_id_c56a18_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RAGQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField(verbose_name="Texto da Consulta")),
                (
                    "query_embedding",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Embedding da Consulta"
                    ),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        default=5, verbose_name="Top K Resultados"),
                ),
                (
                    "similarity_threshold",
                    models.FloatField(
                        default=0.7, verbose_name="Threshold de Similaridade"
                    ),
                ),
                (
                    "filter_categories",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Categorias Filtradas"
                    ),
                ),
                (
                    "filter_tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tags Filtradas"
                    ),
                ),
                (
                    "retrieved_chunks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Chunks Recuperados"
                    ),
                ),
                (
                    "chunk_count",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade de Chunks"),
                ),
                (
                    "llm_response",
                    models.TextField(
                        blank=True, verbose_name="Resposta do LLM"),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Provedor LLM"
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modelo LLM"
                    ),
                ),
                (
                    "search_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tempo de Busca (ms)"
                    ),
                ),
                (
                    "llm_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tempo LLM (ms)"
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total de Tokens"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "etp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_queries",
                        to="documents.document",
                        verbose_name="Documento Relacionado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_queries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta RAG",
                "verbose_name_plural": "Consultas RAG",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="rag_ragquer_user_id_cfb3d2_idx",
                    ),
                    models.Index(fields=["etp"],
                                 name="rag_ragquer_etp_id_adbd24_idx"),
                ],
            },
        ),
    ]
