# Generated by Django 5.0.1 on 2025-11-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0005_rename_documents_etp_user_id_6a6aaa_idx_documents_d_user_id_200c84_idx_and_more",
        ),
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragcontext",
            name="etp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_contexts",
                to="documents.document",
                verbose_name="ETP Relacionado",
            ),
        ),
        migrations.AlterField(
            model_name="ragquery",
            name="etp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_queries",
                to="documents.document",
                verbose_name="ETP Relacionado",
            ),
        ),
    ]
