# Generated by Django 5.0.1 on 2025-10-23 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntelligentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        help_text="Descrição do que o usuário deseja contratar/analisar",
                        verbose_name="Objetivo da Contratação",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("etp", "Estudo Técnico Preliminar"),
                            ("edital", "Edital de Licitação"),
                            ("contrato", "Contrato"),
                        ],
                        default="etp",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Inicializada"),
                            ("uploading", "Upload de Documentos"),
                            ("processing", "Processando Documentos"),
                            ("generating", "Gerando Seções"),
                            ("validating", "Validando"),
                            ("formatting", "Formatando"),
                            ("completed", "Concluída"),
                            ("failed", "Falhou"),
                        ],
                        default="initialized",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "kb_collection_id",
                    models.CharField(
                        help_text="Identificador único da coleção no ChromaDB",
                        max_length=255,
                        verbose_name="ID da Coleção na KB",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligent_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão do Assistente Inteligente",
                "verbose_name_plural": "Sessões do Assistente Inteligente",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_number",
                    models.IntegerField(
                        help_text="1-15 para ETP", verbose_name="Número da Seção"
                    ),
                ),
                (
                    "section_name",
                    models.CharField(max_length=100, verbose_name="Nome da Seção"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Conteúdo gerado pelo agente", verbose_name="Conteúdo"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Se passou na validação",
                        verbose_name="É Válida?",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de erros encontrados pelo validador",
                        verbose_name="Erros de Validação",
                    ),
                ),
                (
                    "validation_warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de avisos encontrados pelo validador",
                        verbose_name="Avisos de Validação",
                    ),
                ),
                (
                    "agent_reasoning",
                    models.TextField(
                        blank=True,
                        help_text="Log do raciocínio usado pelo agente para gerar a seção",
                        verbose_name="Raciocínio do Agente",
                    ),
                ),
                (
                    "generation_attempts",
                    models.IntegerField(
                        default=1,
                        help_text="Número de vezes que o agente tentou gerar esta seção",
                        verbose_name="Tentativas de Geração",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_sections",
                        to="intelligent_assistant.intelligentsession",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção Gerada",
                "verbose_name_plural": "Seções Geradas",
                "ordering": ["session", "section_number"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "docx_file",
                    models.FileField(
                        upload_to="intelligent_assistant/generated/%Y/%m/%d/",
                        verbose_name="Arquivo DOCX",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="intelligent_assistant/generated/%Y/%m/%d/",
                        verbose_name="Arquivo PDF",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informações sobre o documento gerado",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "file_size_docx",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tamanho DOCX (bytes)"
                    ),
                ),
                (
                    "file_size_pdf",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tamanho PDF (bytes)"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gerado em"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_documents",
                        to="intelligent_assistant.intelligentsession",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Gerado",
                "verbose_name_plural": "Documentos Gerados",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="intelligent_assistant/uploads/%Y/%m/%d/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Nome do Arquivo"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("txt", "Texto"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Arquivo",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        help_text="Tamanho em bytes",
                        verbose_name="Tamanho do Arquivo (bytes)",
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Texto extraído do documento",
                        verbose_name="Texto Extraído",
                    ),
                ),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Extração",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to="intelligent_assistant.intelligentsession",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Enviado",
                "verbose_name_plural": "Documentos Enviados",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="intelligentsession",
            index=models.Index(
                fields=["-created_at"], name="intelligent_created_4199a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intelligentsession",
            index=models.Index(
                fields=["user", "-created_at"], name="intelligent_user_id_f61ce8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intelligentsession",
            index=models.Index(fields=["status"], name="intelligent_status_72ce71_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedsection",
            index=models.Index(
                fields=["session", "section_number"],
                name="intelligent_session_1f209a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="generatedsection",
            unique_together={("session", "section_number")},
        ),
    ]
