# Generated by Django 5.0.1 on 2025-12-09 21:06

import django.db.models.deletion
import pgvector.django
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0002_enable_pgvector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome identificador da base de conhecimento",
                        max_length=255,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do conteúdo da base de conhecimento",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se a base está disponível para uso",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_bases_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base de Conhecimento",
                "verbose_name_plural": "Bases de Conhecimento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Posição do chunk no documento original",
                        verbose_name="Índice do Chunk",
                    ),
                ),
                (
                    "chunk_text",
                    models.TextField(
                        help_text="Conteúdo textual do chunk",
                        verbose_name="Texto do Chunk",
                    ),
                ),
                (
                    "chunk_size",
                    models.IntegerField(
                        help_text="Número de caracteres no chunk",
                        verbose_name="Tamanho do Chunk",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        dimensions=1536,
                        help_text="Vetor de embedding do chunk (1536 dimensões)",
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-3-small",
                        help_text="Modelo usado para gerar o embedding",
                        max_length=100,
                        verbose_name="Modelo de Embedding",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informações adicionais sobre o chunk (página, seção, etc)",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="intelligent_assistant.uploadeddocument",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="intelligent_assistant.intelligentsession",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding de Documento",
                "verbose_name_plural": "Embeddings de Documentos",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["session"], name="intelligent_session_8b855e_idx"
                    ),
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="intelligent_documen_387120_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        help_text="Nome do arquivo/documento original",
                        max_length=255,
                        verbose_name="Nome da Fonte",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("txt", "Texto"),
                            ("url", "URL/Webpage"),
                            ("manual", "Entrada Manual"),
                        ],
                        max_length=50,
                        verbose_name="Tipo da Fonte",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="Índice do Chunk")),
                ("chunk_text", models.TextField(verbose_name="Texto do Chunk")),
                ("chunk_size", models.IntegerField(verbose_name="Tamanho do Chunk")),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        dimensions=1536, verbose_name="Embedding Vector"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-3-small",
                        max_length=100,
                        verbose_name="Modelo de Embedding",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadados"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="intelligent_assistant.knowledgebase",
                        verbose_name="Base de Conhecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding da Base de Conhecimento",
                "verbose_name_plural": "Embeddings da Base de Conhecimento",
                "ordering": ["knowledge_base", "source_name", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["knowledge_base"], name="intelligent_knowled_ab551c_idx"
                    ),
                    models.Index(
                        fields=["source_name"], name="intelligent_source__7a3d4c_idx"
                    ),
                ],
            },
        ),
    ]
