# Generated by Django 5.0.1 on 2025-12-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0003_add_embedding_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateddocument",
            name="docx_generated",
            field=models.BooleanField(default=False, verbose_name="DOCX Gerado"),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="docx_url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="URL do DOCX no R2"
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="file_size_markdown",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Tamanho Markdown (bytes)"
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="markdown_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Documento ETP completo em formato Markdown",
                verbose_name="Conteúdo Markdown",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="overall_score",
            field=models.FloatField(
                blank=True,
                help_text="Média das validações de todas as seções (0-100)",
                null=True,
                verbose_name="Score Geral",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="pdf_generated",
            field=models.BooleanField(
                default=False,
                help_text="Se o PDF foi gerado e enviado ao R2",
                verbose_name="PDF Gerado",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="pdf_url",
            field=models.URLField(
                blank=True,
                help_text="URL pública do PDF armazenado no Cloudflare R2",
                max_length=1000,
                null=True,
                verbose_name="URL do PDF no R2",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Título do Documento",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="total_sections",
            field=models.IntegerField(
                default=15,
                help_text="Número total de seções do documento",
                verbose_name="Total de Seções",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="valid_sections_count",
            field=models.IntegerField(
                default=0,
                help_text="Número de seções que passaram na validação",
                verbose_name="Seções Válidas",
            ),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="intelligent_assistant/generated/%Y/%m/%d/",
                verbose_name="Arquivo DOCX",
            ),
        ),
    ]
