# Generated by Django 5.0.1 on 2025-12-26 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0004_add_markdown_fields_to_generated_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBlueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Nome do blueprint (ex: "ETP PMJP - Lei 14.133", "ETP Rio de Janeiro")',
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do blueprint e seu propósito",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("etp", "Estudo Técnico Preliminar"),
                            ("termo_referencia", "Termo de Referência"),
                            ("edital", "Edital de Licitação"),
                            ("contrato", "Contrato"),
                            ("parecer", "Parecer Técnico"),
                            ("projeto_basico", "Projeto Básico"),
                            ("custom", "Customizado"),
                        ],
                        default="etp",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Versão do blueprint",
                        max_length=50,
                        verbose_name="Versão",
                    ),
                ),
                (
                    "legal_basis",
                    models.TextField(
                        blank=True,
                        help_text="Legislação base (ex: Lei 14.133/2021, Decreto 10.024/2019)",
                        verbose_name="Base Legal",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configurações adicionais em JSON",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o blueprint está disponível para uso",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Se é o blueprint padrão para seu tipo de documento",
                        verbose_name="Padrão",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_blueprints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blueprint de Documento",
                "verbose_name_plural": "Blueprints de Documentos",
                "ordering": ["document_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlueprintSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_number",
                    models.IntegerField(
                        help_text="Número identificador da seção (ex: 1, 2, 3...)",
                        verbose_name="Número da Seção",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        help_text='Nome da seção (ex: "Descrição da Necessidade da Contratação")',
                        max_length=255,
                        verbose_name="Nome da Seção",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        help_text='Identificador único dentro do blueprint (ex: "section_01", "descricao_necessidade")',
                        max_length=100,
                        verbose_name="Chave da Seção",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do que deve conter esta seção",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instruções específicas para o preenchimento desta seção",
                        verbose_name="Instruções",
                    ),
                ),
                (
                    "legal_reference",
                    models.TextField(
                        blank=True,
                        help_text="Artigos e incisos que fundamentam esta seção",
                        verbose_name="Referência Legal",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Ordem de exibição/geração (menor = primeiro)",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Se a seção é obrigatória no documento final",
                        verbose_name="Obrigatória",
                    ),
                ),
                (
                    "allow_skip",
                    models.BooleanField(
                        default=True,
                        help_text="Se o usuário pode optar por não gerar esta seção",
                        verbose_name="Permitir Pular",
                    ),
                ),
                (
                    "max_generation_attempts",
                    models.IntegerField(
                        default=3,
                        help_text="Número máximo de tentativas de geração em caso de falha",
                        verbose_name="Máximo de Tentativas",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se a seção está disponível",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="intelligent_assistant.documentblueprint",
                        verbose_name="Blueprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção do Blueprint",
                "verbose_name_plural": "Seções do Blueprint",
                "ordering": ["blueprint", "order", "section_number"],
            },
        ),
        migrations.CreateModel(
            name="GenerationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        help_text="Objetivo/contexto fornecido pelo usuário",
                        verbose_name="Objetivo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Inicializada"),
                            ("sections_selected", "Seções Selecionadas"),
                            ("generating", "Gerando"),
                            ("validating", "Validando"),
                            ("completed", "Concluída"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="initialized",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configurações adicionais da sessão",
                        verbose_name="Configurações",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_sessions",
                        to="intelligent_assistant.documentblueprint",
                        verbose_name="Blueprint",
                    ),
                ),
                (
                    "intelligent_session",
                    models.OneToOneField(
                        blank=True,
                        help_text="Sessão do sistema legado, se existir",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dynamic_generation",
                        to="intelligent_assistant.intelligentsession",
                        verbose_name="Sessão Inteligente",
                    ),
                ),
                (
                    "selected_sections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Seções que o usuário escolheu gerar",
                        related_name="selected_in_sessions",
                        to="intelligent_assistant.blueprintsection",
                        verbose_name="Seções Selecionadas",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Geração",
                "verbose_name_plural": "Sessões de Geração",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SectionAgentConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Nome descritivo do agente (ex: "Gerador Seção 1 - Descrição da Necessidade")',
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do propósito do agente",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("generator", "Gerador de Conteúdo"),
                            ("validator", "Validador de Conteúdo"),
                        ],
                        default="generator",
                        max_length=20,
                        verbose_name="Tipo de Agente",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Instruções do sistema para o agente. Define o papel e comportamento.",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Template do prompt do usuário. Use {{variavel}} para placeholders. Variáveis disponíveis: {{objective}}, {{context}}, {{previous_sections}}, {{current_content}}, {{section_name}}, {{section_number}}",
                        verbose_name="User Prompt Template",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        default="anthropic",
                        max_length=20,
                        verbose_name="Provedor LLM",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="claude-3-5-sonnet-20241022",
                        help_text="Nome do modelo (ex: claude-3-5-sonnet-20241022, gpt-4o)",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="0.0 = determinístico, 2.0 = criativo",
                        verbose_name="Temperature",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=4000,
                        help_text="Limite máximo de tokens na resposta",
                        verbose_name="Max Tokens",
                    ),
                ),
                (
                    "use_rag",
                    models.BooleanField(
                        default=True,
                        help_text="Buscar contexto relevante na base de conhecimento",
                        verbose_name="Usar RAG",
                    ),
                ),
                (
                    "rag_query_template",
                    models.TextField(
                        blank=True,
                        help_text="Template para buscar contexto. Use {{variavel}} para placeholders.",
                        verbose_name="Template de Query RAG",
                    ),
                ),
                (
                    "rag_top_k",
                    models.IntegerField(
                        default=5,
                        help_text="Número de chunks mais relevantes a recuperar",
                        verbose_name="RAG Top K",
                    ),
                ),
                (
                    "rag_similarity_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Similaridade mínima para incluir um chunk (0.0 a 1.0)",
                        verbose_name="RAG Threshold",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o agente está disponível para uso",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Se é o agente padrão para seu tipo",
                        verbose_name="Padrão",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_section_agent_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "knowledge_bases",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Bases de conhecimento específicas para este agente",
                        related_name="section_agent_configs",
                        to="intelligent_assistant.knowledgebase",
                        verbose_name="Bases de Conhecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Agente de Seção",
                "verbose_name_plural": "Configurações de Agentes de Seção",
                "ordering": ["agent_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="blueprintsection",
            name="generator_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agente responsável por gerar o conteúdo desta seção",
                limit_choices_to={"agent_type": "generator", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generator_for_sections",
                to="intelligent_assistant.sectionagentconfig",
                verbose_name="Agente Gerador",
            ),
        ),
        migrations.AddField(
            model_name="blueprintsection",
            name="validator_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agente responsável por validar o conteúdo gerado",
                limit_choices_to={"agent_type": "validator", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validator_for_sections",
                to="intelligent_assistant.sectionagentconfig",
                verbose_name="Agente Validador",
            ),
        ),
        migrations.CreateModel(
            name="SectionGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("generating", "Gerando"),
                            ("generated", "Gerado"),
                            ("validating", "Validando"),
                            ("validated", "Validado"),
                            ("failed", "Falhou"),
                            ("skipped", "Pulada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Conteúdo gerado pelo agente",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=False, verbose_name="É Válido?"),
                ),
                (
                    "validation_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de 0 a 100",
                        null=True,
                        verbose_name="Score de Validação",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Erros de Validação"
                    ),
                ),
                (
                    "validation_warnings",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Avisos de Validação"
                    ),
                ),
                (
                    "validation_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Feedback detalhado do validador",
                        verbose_name="Feedback da Validação",
                    ),
                ),
                (
                    "generation_attempts",
                    models.IntegerField(
                        default=0, verbose_name="Tentativas de Geração"
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Total de tokens consumidos (input + output)",
                        verbose_name="Tokens Usados",
                    ),
                ),
                (
                    "generation_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tempo de Geração (ms)"
                    ),
                ),
                (
                    "validation_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tempo de Validação (ms)"
                    ),
                ),
                (
                    "agent_reasoning",
                    models.TextField(
                        blank=True,
                        help_text="Log do processo de raciocínio do agente",
                        verbose_name="Raciocínio do Agente",
                    ),
                ),
                (
                    "rag_context_used",
                    models.TextField(
                        blank=True,
                        help_text="Chunks de contexto recuperados pelo RAG",
                        verbose_name="Contexto RAG Utilizado",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generations",
                        to="intelligent_assistant.blueprintsection",
                        verbose_name="Seção",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_generations",
                        to="intelligent_assistant.generationsession",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geração de Seção",
                "verbose_name_plural": "Gerações de Seções",
                "ordering": ["session", "section__order"],
            },
        ),
        migrations.AddIndex(
            model_name="documentblueprint",
            index=models.Index(
                fields=["document_type", "is_active"],
                name="intelligent_documen_7be6b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentblueprint",
            index=models.Index(
                fields=["is_active"], name="intelligent_is_acti_a4ce09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationsession",
            index=models.Index(
                fields=["user", "-created_at"], name="intelligent_user_id_81752c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationsession",
            index=models.Index(fields=["status"], name="intelligent_status_42aaf5_idx"),
        ),
        migrations.AddIndex(
            model_name="generationsession",
            index=models.Index(
                fields=["blueprint", "status"], name="intelligent_bluepri_ae6a57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionagentconfig",
            index=models.Index(
                fields=["agent_type", "is_active"],
                name="intelligent_agent_t_0578df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sectionagentconfig",
            index=models.Index(
                fields=["is_active"], name="intelligent_is_acti_32cff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blueprintsection",
            index=models.Index(
                fields=["blueprint", "order"], name="intelligent_bluepri_3e5d78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blueprintsection",
            index=models.Index(
                fields=["is_active"], name="intelligent_is_acti_a4dfe1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blueprintsection",
            unique_together={
                ("blueprint", "section_key"),
                ("blueprint", "section_number"),
            },
        ),
        migrations.AddIndex(
            model_name="sectiongeneration",
            index=models.Index(
                fields=["session", "status"], name="intelligent_session_4f9d7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectiongeneration",
            index=models.Index(fields=["status"], name="intelligent_status_9494ad_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sectiongeneration",
            unique_together={("session", "section")},
        ),
    ]
