# Generated by Django 5.0.1 on 2025-12-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "intelligent_assistant",
            "0005_documentblueprint_blueprintsection_generationsession_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentblueprint",
            name="custom_css",
            field=models.TextField(
                blank=True,
                help_text="CSS adicional para personalização avançada do PDF",
                verbose_name="CSS Customizado",
            ),
        ),
        migrations.AddField(
            model_name="documentblueprint",
            name="footer_text",
            field=models.TextField(
                blank=True,
                help_text="Texto do rodapé com legislação aplicável",
                verbose_name="Texto do Rodapé",
            ),
        ),
        migrations.AddField(
            model_name="documentblueprint",
            name="header_text",
            field=models.CharField(
                blank=True,
                help_text='Texto exibido no topo de cada página (ex: "GOVERNO DO ESTADO DO RIO DE JANEIRO")',
                max_length=255,
                verbose_name="Texto do Cabeçalho",
            ),
        ),
        migrations.AddField(
            model_name="documentblueprint",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo do órgão para o cabeçalho do documento",
                null=True,
                upload_to="blueprints/logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="documentblueprint",
            name="organization_acronym",
            field=models.CharField(
                blank=True,
                help_text='Sigla da organização (ex: "PMJP", "PRODERJ")',
                max_length=50,
                verbose_name="Sigla",
            ),
        ),
        migrations.AddField(
            model_name="documentblueprint",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text='Nome do órgão/entidade (ex: "Prefeitura Municipal de João Pessoa")',
                max_length=255,
                verbose_name="Nome da Organização",
            ),
        ),
        migrations.AddField(
            model_name="documentblueprint",
            name="primary_color",
            field=models.CharField(
                default="#1a365d",
                help_text="Cor principal dos títulos (formato hex: #RRGGBB)",
                max_length=7,
                verbose_name="Cor Primária",
            ),
        ),
        migrations.AddField(
            model_name="documentblueprint",
            name="secondary_color",
            field=models.CharField(
                default="#2c5282",
                help_text="Cor dos subtítulos e destaques (formato hex: #RRGGBB)",
                max_length=7,
                verbose_name="Cor Secundária",
            ),
        ),
    ]
