# Generated by Django 5.0.1 on 2025-12-29 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0006_add_blueprint_pdf_customization"),
    ]

    operations = [
        migrations.AddField(
            model_name="intelligentsession",
            name="blueprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Modelo de documento selecionado para esta sessão",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="intelligent_assistant.documentblueprint",
                verbose_name="Blueprint",
            ),
        ),
        migrations.AlterField(
            model_name="documentblueprint",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("etp", "Estudo Técnico Preliminar"),
                    ("termo_referencia", "Termo de Referência"),
                    ("edital", "Edital de Licitação"),
                    ("contrato", "Contrato"),
                    ("parecer", "Parecer Técnico"),
                    ("parecer_juridico", "Parecer Jurídico"),
                    ("projeto_basico", "Projeto Básico"),
                    ("custom", "Customizado"),
                ],
                default="etp",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="intelligentsession",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("etp", "Estudo Técnico Preliminar"),
                    ("termo_referencia", "Termo de Referência"),
                    ("edital", "Edital de Licitação"),
                    ("contrato", "Contrato"),
                    ("parecer", "Parecer Técnico"),
                    ("parecer_juridico", "Parecer Jurídico"),
                    ("projeto_basico", "Projeto Básico"),
                    ("custom", "Customizado"),
                ],
                default="etp",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
