"""
Migration para adicionar Blueprints da Lei 14.133/2021

Este migration cria os blueprints para todos os documentos do processo licitatorio:
- Fase Preparatoria: DFD, Mapa de Riscos, Pesquisa de Precos
- Fase Externa: Ata de Sessao, Pareceres, Termos
- Impugnacoes e Recursos
- Pos-Contratacao
"""

from django.db import migrations
import uuid


# =============================================================================
# DEFINICAO DOS BLUEPRINTS E SUAS SECOES
# =============================================================================

BLUEPRINTS_DATA = [
    # =========================================================================
    # 1. DOCUMENTO DE FORMALIZACAO DE DEMANDA (DFD)
    # =========================================================================
    {
        'name': 'Documento de Formalizacao de Demanda - Lei 14.133',
        'description': 'Documento que formaliza a necessidade de contratacao, conforme Art. 18, inciso I da Lei 14.133/2021.',
        'document_type': 'dfd',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 18, inciso I; IN SEGES/ME 58/2022',
        'is_active': True,
        'is_default': True,
        'organization_name': '',
        'primary_color': '#1a365d',
        'secondary_color': '#2c5282',
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao_requisitante',
                'section_name': 'Identificacao do Requisitante',
                'description': 'Identificacao da area requisitante e responsavel pela demanda.',
                'instructions': 'Informe o setor/unidade requisitante, nome do responsavel, cargo, matricula e contatos.',
                'legal_reference': 'Art. 18, inciso I - identificacao do requisitante',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'justificativa_necessidade',
                'section_name': 'Justificativa da Necessidade',
                'description': 'Fundamentacao da necessidade da contratacao para o interesse publico.',
                'instructions': 'Descreva de forma clara e objetiva por que a contratacao e necessaria, qual problema sera resolvido e quais os beneficios esperados.',
                'legal_reference': 'Art. 18, inciso I - demonstracao da necessidade',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'descricao_objeto',
                'section_name': 'Descricao do Objeto',
                'description': 'Descricao clara e precisa do que se pretende contratar.',
                'instructions': 'Descreva o objeto de forma detalhada, incluindo especificacoes tecnicas quando aplicavel.',
                'legal_reference': 'Art. 18, inciso I - descricao sucinta do objeto',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'quantidade_estimada',
                'section_name': 'Quantidade Estimada',
                'description': 'Estimativa de quantidade a ser contratada.',
                'instructions': 'Informe a quantidade estimada com base em historico de consumo, demanda projetada ou levantamento especifico.',
                'legal_reference': 'Art. 18, inciso I - quantidade a ser contratada',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'previsao_data',
                'section_name': 'Previsao de Data',
                'description': 'Previsao de quando a contratacao devera ser efetivada.',
                'instructions': 'Indique a data ou periodo previsto para inicio da contratacao e justifique a urgencia, se houver.',
                'legal_reference': 'Art. 18, inciso I - previsao de data',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'estimativa_valor',
                'section_name': 'Estimativa Preliminar de Valor',
                'description': 'Estimativa inicial de valor da contratacao.',
                'instructions': 'Informe uma estimativa preliminar de valor, se disponivel, com base em contratacoes anteriores ou pesquisa inicial.',
                'legal_reference': 'Art. 18, inciso I - estimativa preliminar de valor',
                'is_required': False,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'grau_prioridade',
                'section_name': 'Grau de Prioridade',
                'description': 'Nivel de prioridade e urgencia da contratacao.',
                'instructions': 'Classifique a prioridade (Alta, Media, Baixa) e justifique.',
                'legal_reference': 'Art. 18, inciso I - grau de prioridade',
                'is_required': True,
                'order': 7,
            },
            {
                'section_number': 8,
                'section_key': 'alinhamento_estrategico',
                'section_name': 'Alinhamento Estrategico',
                'description': 'Vinculacao com o planejamento estrategico institucional.',
                'instructions': 'Demonstre como a contratacao se alinha aos objetivos estrategicos, PCA ou instrumentos de planejamento.',
                'legal_reference': 'Art. 18, inciso I - alinhamento com o planejamento',
                'is_required': False,
                'order': 8,
            },
            {
                'section_number': 9,
                'section_key': 'aprovacao_autoridade',
                'section_name': 'Aprovacao da Autoridade',
                'description': 'Aprovacao pela autoridade competente.',
                'instructions': 'Espaco para assinatura e aprovacao da autoridade competente da area requisitante.',
                'legal_reference': 'Art. 18, inciso I - aprovacao da autoridade',
                'is_required': True,
                'order': 9,
            },
        ]
    },

    # =========================================================================
    # 2. MAPA DE RISCOS
    # =========================================================================
    {
        'name': 'Mapa de Riscos - Lei 14.133',
        'description': 'Mapa de riscos da contratacao conforme Art. 18, inciso X da Lei 14.133/2021.',
        'document_type': 'mapa_riscos',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 18, inciso X; IN SEGES/ME 58/2022, Art. 7',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao_processo',
                'section_name': 'Identificacao do Processo',
                'description': 'Identificacao do processo licitatorio e objeto.',
                'instructions': 'Informe numero do processo, objeto resumido e responsaveis pela elaboracao.',
                'legal_reference': 'IN 58/2022, Art. 7',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'metodologia',
                'section_name': 'Metodologia de Analise de Riscos',
                'description': 'Descricao da metodologia utilizada para identificacao e analise dos riscos.',
                'instructions': 'Descreva a metodologia utilizada (matriz de probabilidade x impacto, SWOT, etc).',
                'legal_reference': 'IN 58/2022, Art. 7, I',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'riscos_planejamento',
                'section_name': 'Riscos da Fase de Planejamento',
                'description': 'Riscos identificados na fase de planejamento da contratacao.',
                'instructions': 'Liste os riscos da fase de planejamento com probabilidade, impacto e acoes de mitigacao.',
                'legal_reference': 'IN 58/2022, Art. 7, II',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'riscos_selecao',
                'section_name': 'Riscos da Fase de Selecao',
                'description': 'Riscos identificados na fase de selecao do fornecedor.',
                'instructions': 'Liste os riscos da fase de licitacao/selecao com probabilidade, impacto e acoes de mitigacao.',
                'legal_reference': 'IN 58/2022, Art. 7, II',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'riscos_execucao',
                'section_name': 'Riscos da Fase de Execucao',
                'description': 'Riscos identificados na fase de execucao contratual.',
                'instructions': 'Liste os riscos da fase de execucao com probabilidade, impacto e acoes de mitigacao.',
                'legal_reference': 'IN 58/2022, Art. 7, II',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'matriz_riscos',
                'section_name': 'Matriz de Riscos Consolidada',
                'description': 'Consolidacao de todos os riscos em matriz unica.',
                'instructions': 'Apresente a matriz consolidada com classificacao de criticidade.',
                'legal_reference': 'IN 58/2022, Art. 7, III',
                'is_required': True,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'plano_contingencia',
                'section_name': 'Plano de Contingencia',
                'description': 'Acoes de contingencia para riscos de alta criticidade.',
                'instructions': 'Descreva as acoes de contingencia para os riscos classificados como criticos.',
                'legal_reference': 'IN 58/2022, Art. 7, IV',
                'is_required': True,
                'order': 7,
            },
            {
                'section_number': 8,
                'section_key': 'responsaveis_monitoramento',
                'section_name': 'Responsaveis pelo Monitoramento',
                'description': 'Definicao dos responsaveis pelo monitoramento dos riscos.',
                'instructions': 'Indique os responsaveis pelo monitoramento continuo de cada risco.',
                'legal_reference': 'IN 58/2022, Art. 7, V',
                'is_required': True,
                'order': 8,
            },
        ]
    },

    # =========================================================================
    # 3. PESQUISA DE PRECOS
    # =========================================================================
    {
        'name': 'Pesquisa de Precos - Lei 14.133',
        'description': 'Pesquisa de precos para estimativa de valor da contratacao conforme Art. 23 da Lei 14.133/2021.',
        'document_type': 'pesquisa_precos',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 23; IN SEGES/ME 65/2021',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao_objeto',
                'section_name': 'Identificacao do Objeto',
                'description': 'Identificacao do objeto da pesquisa de precos.',
                'instructions': 'Descreva o objeto, especificacoes e unidade de medida.',
                'legal_reference': 'IN 65/2021, Art. 2',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'metodologia_pesquisa',
                'section_name': 'Metodologia da Pesquisa',
                'description': 'Descricao da metodologia utilizada na pesquisa.',
                'instructions': 'Indique os parametros utilizados: PNCP, contratacoes similares, fornecedores, etc.',
                'legal_reference': 'IN 65/2021, Art. 5',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'fontes_pncp',
                'section_name': 'Consulta ao PNCP',
                'description': 'Precos obtidos em contratacoes publicas via PNCP.',
                'instructions': 'Apresente os precos encontrados no PNCP para o mesmo objeto ou similar.',
                'legal_reference': 'Lei 14.133/2021, Art. 23, I',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'contratacoes_similares',
                'section_name': 'Contratacoes Similares',
                'description': 'Precos de contratacoes similares do proprio orgao.',
                'instructions': 'Apresente precos de contratacoes anteriores do orgao para objeto igual ou similar.',
                'legal_reference': 'Lei 14.133/2021, Art. 23, II',
                'is_required': False,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'cotacoes_fornecedores',
                'section_name': 'Cotacoes de Fornecedores',
                'description': 'Cotacoes obtidas diretamente com fornecedores.',
                'instructions': 'Apresente no minimo 3 cotacoes de fornecedores distintos.',
                'legal_reference': 'Lei 14.133/2021, Art. 23, IV',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'pesquisa_mercado',
                'section_name': 'Pesquisa de Mercado',
                'description': 'Pesquisa em sites especializados, catalogos, etc.',
                'instructions': 'Apresente precos de pesquisa em sites, catalogos ou tabelas de referencia.',
                'legal_reference': 'Lei 14.133/2021, Art. 23, V',
                'is_required': False,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'analise_precos',
                'section_name': 'Analise Critica dos Precos',
                'description': 'Analise critica dos precos coletados.',
                'instructions': 'Analise a consistencia dos precos, descarte valores inexequiveis ou excessivos.',
                'legal_reference': 'IN 65/2021, Art. 6',
                'is_required': True,
                'order': 7,
            },
            {
                'section_number': 8,
                'section_key': 'calculo_estimativa',
                'section_name': 'Calculo da Estimativa',
                'description': 'Calculo do valor estimado da contratacao.',
                'instructions': 'Apresente o calculo (media, mediana ou menor preco) e justifique o metodo escolhido.',
                'legal_reference': 'IN 65/2021, Art. 6, par. 1',
                'is_required': True,
                'order': 8,
            },
            {
                'section_number': 9,
                'section_key': 'valor_total_estimado',
                'section_name': 'Valor Total Estimado',
                'description': 'Valor total estimado da contratacao.',
                'instructions': 'Apresente o valor total estimado e sua composicao.',
                'legal_reference': 'Lei 14.133/2021, Art. 23',
                'is_required': True,
                'order': 9,
            },
            {
                'section_number': 10,
                'section_key': 'documentacao_anexa',
                'section_name': 'Documentacao Anexa',
                'description': 'Lista de documentos anexos a pesquisa.',
                'instructions': 'Liste todos os documentos que compoem a pesquisa (cotacoes, prints, etc).',
                'legal_reference': 'IN 65/2021, Art. 7',
                'is_required': True,
                'order': 10,
            },
        ]
    },

    # =========================================================================
    # 4. ATA DE SESSAO PUBLICA
    # =========================================================================
    {
        'name': 'Ata de Sessao Publica - Lei 14.133',
        'description': 'Ata da sessao publica de licitacao conforme Lei 14.133/2021.',
        'document_type': 'ata_sessao',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 17, par. 2; Decreto 10.024/2019',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'abertura_sessao',
                'section_name': 'Abertura da Sessao',
                'description': 'Registro da abertura da sessao publica.',
                'instructions': 'Registre data, hora, local (presencial ou eletronico), pregoeiro/agente e equipe.',
                'legal_reference': 'Lei 14.133/2021, Art. 17',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'objeto_licitacao',
                'section_name': 'Objeto da Licitacao',
                'description': 'Identificacao do objeto licitado.',
                'instructions': 'Informe numero do processo, modalidade, objeto resumido.',
                'legal_reference': 'Lei 14.133/2021, Art. 17',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'participantes',
                'section_name': 'Participantes/Licitantes',
                'description': 'Relacao dos licitantes participantes.',
                'instructions': 'Liste os licitantes que participaram com CNPJ/CPF e representantes.',
                'legal_reference': 'Lei 14.133/2021, Art. 17',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'analise_propostas',
                'section_name': 'Analise das Propostas',
                'description': 'Registro da analise das propostas iniciais.',
                'instructions': 'Registre as propostas apresentadas, valores e analise de conformidade.',
                'legal_reference': 'Lei 14.133/2021, Art. 59',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'fase_lances',
                'section_name': 'Fase de Lances',
                'description': 'Registro da fase competitiva de lances.',
                'instructions': 'Registre os lances ofertados, ordem e valores finais.',
                'legal_reference': 'Lei 14.133/2021, Art. 56',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'negociacao',
                'section_name': 'Negociacao',
                'description': 'Registro de negociacao com o primeiro colocado.',
                'instructions': 'Registre eventuais negociacoes realizadas e resultado.',
                'legal_reference': 'Lei 14.133/2021, Art. 61',
                'is_required': False,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'habilitacao',
                'section_name': 'Fase de Habilitacao',
                'description': 'Registro da analise de habilitacao.',
                'instructions': 'Registre a analise dos documentos de habilitacao e resultado.',
                'legal_reference': 'Lei 14.133/2021, Art. 62-70',
                'is_required': True,
                'order': 7,
            },
            {
                'section_number': 8,
                'section_key': 'declaracao_vencedor',
                'section_name': 'Declaracao do Vencedor',
                'description': 'Declaracao do licitante vencedor.',
                'instructions': 'Registre a declaracao do vencedor provisorio com valor final.',
                'legal_reference': 'Lei 14.133/2021, Art. 17, par. 2',
                'is_required': True,
                'order': 8,
            },
            {
                'section_number': 9,
                'section_key': 'manifestacao_recursos',
                'section_name': 'Manifestacao de Intencao de Recurso',
                'description': 'Registro de intencoes de recurso.',
                'instructions': 'Registre se houve manifestacao de intencao de recurso e por quem.',
                'legal_reference': 'Lei 14.133/2021, Art. 165',
                'is_required': True,
                'order': 9,
            },
            {
                'section_number': 10,
                'section_key': 'encerramento',
                'section_name': 'Encerramento da Sessao',
                'description': 'Registro do encerramento da sessao.',
                'instructions': 'Registre o encerramento, proximos passos e assinaturas.',
                'legal_reference': 'Lei 14.133/2021, Art. 17',
                'is_required': True,
                'order': 10,
            },
        ]
    },

    # =========================================================================
    # 5. PARECER DE JULGAMENTO
    # =========================================================================
    {
        'name': 'Parecer de Julgamento de Propostas - Lei 14.133',
        'description': 'Parecer tecnico de julgamento das propostas conforme Lei 14.133/2021.',
        'document_type': 'parecer_julgamento',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 59-61',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao_processo',
                'section_name': 'Identificacao do Processo',
                'description': 'Identificacao do processo licitatorio.',
                'instructions': 'Informe numero do processo, modalidade, objeto e criterio de julgamento.',
                'legal_reference': 'Lei 14.133/2021, Art. 59',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'objeto_analise',
                'section_name': 'Objeto da Analise',
                'description': 'Descricao do objeto em analise.',
                'instructions': 'Descreva o objeto licitado e suas especificacoes principais.',
                'legal_reference': 'Lei 14.133/2021, Art. 59',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'propostas_recebidas',
                'section_name': 'Propostas Recebidas',
                'description': 'Relacao das propostas recebidas.',
                'instructions': 'Liste todas as propostas com identificacao do licitante e valor.',
                'legal_reference': 'Lei 14.133/2021, Art. 59',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'analise_conformidade',
                'section_name': 'Analise de Conformidade',
                'description': 'Analise de conformidade das propostas com o edital.',
                'instructions': 'Analise cada proposta quanto ao atendimento das exigencias do edital.',
                'legal_reference': 'Lei 14.133/2021, Art. 59, par. 1',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'analise_exequibilidade',
                'section_name': 'Analise de Exequibilidade',
                'description': 'Verificacao da exequibilidade dos precos.',
                'instructions': 'Analise se os precos sao exequiveis, conforme parametros legais.',
                'legal_reference': 'Lei 14.133/2021, Art. 59, par. 4',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'classificacao',
                'section_name': 'Classificacao das Propostas',
                'description': 'Ordem de classificacao das propostas.',
                'instructions': 'Apresente a ordem de classificacao conforme criterio de julgamento.',
                'legal_reference': 'Lei 14.133/2021, Art. 60',
                'is_required': True,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'fundamentacao',
                'section_name': 'Fundamentacao Legal',
                'description': 'Fundamentacao legal da analise.',
                'instructions': 'Fundamente a analise com base na legislacao e no edital.',
                'legal_reference': 'Lei 14.133/2021, Art. 59-61',
                'is_required': True,
                'order': 7,
            },
            {
                'section_number': 8,
                'section_key': 'conclusao',
                'section_name': 'Conclusao e Recomendacao',
                'description': 'Conclusao e recomendacao sobre o julgamento.',
                'instructions': 'Apresente a conclusao e recomendacao quanto a proposta vencedora.',
                'legal_reference': 'Lei 14.133/2021, Art. 61',
                'is_required': True,
                'order': 8,
            },
        ]
    },

    # =========================================================================
    # 6. PARECER DE HABILITACAO
    # =========================================================================
    {
        'name': 'Parecer de Habilitacao - Lei 14.133',
        'description': 'Parecer tecnico de habilitacao dos licitantes conforme Lei 14.133/2021.',
        'document_type': 'parecer_habilitacao',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 62-70',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao_processo',
                'section_name': 'Identificacao do Processo',
                'description': 'Identificacao do processo licitatorio.',
                'instructions': 'Informe numero do processo, modalidade e licitante analisado.',
                'legal_reference': 'Lei 14.133/2021, Art. 62',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'documentos_apresentados',
                'section_name': 'Documentos Apresentados',
                'description': 'Relacao dos documentos de habilitacao apresentados.',
                'instructions': 'Liste todos os documentos apresentados pelo licitante.',
                'legal_reference': 'Lei 14.133/2021, Art. 62-70',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'habilitacao_juridica',
                'section_name': 'Habilitacao Juridica',
                'description': 'Analise da habilitacao juridica.',
                'instructions': 'Analise os documentos de habilitacao juridica (Art. 66).',
                'legal_reference': 'Lei 14.133/2021, Art. 66',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'regularidade_fiscal',
                'section_name': 'Regularidade Fiscal e Trabalhista',
                'description': 'Analise da regularidade fiscal e trabalhista.',
                'instructions': 'Analise certidoes e regularidades fiscais (Art. 68).',
                'legal_reference': 'Lei 14.133/2021, Art. 68',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'qualificacao_economica',
                'section_name': 'Qualificacao Economico-Financeira',
                'description': 'Analise da qualificacao economico-financeira.',
                'instructions': 'Analise balanco, indices e garantias (Art. 69).',
                'legal_reference': 'Lei 14.133/2021, Art. 69',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'qualificacao_tecnica',
                'section_name': 'Qualificacao Tecnica',
                'description': 'Analise da qualificacao tecnica.',
                'instructions': 'Analise atestados, certificacoes e capacidade tecnica (Art. 67).',
                'legal_reference': 'Lei 14.133/2021, Art. 67',
                'is_required': True,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'declaracoes',
                'section_name': 'Declaracoes Exigidas',
                'description': 'Analise das declaracoes obrigatorias.',
                'instructions': 'Verifique declaracoes de ME/EPP, nao emprega menor, etc.',
                'legal_reference': 'Lei 14.133/2021, Art. 63',
                'is_required': True,
                'order': 7,
            },
            {
                'section_number': 8,
                'section_key': 'conclusao',
                'section_name': 'Conclusao',
                'description': 'Conclusao sobre a habilitacao.',
                'instructions': 'Conclua se o licitante esta HABILITADO ou INABILITADO.',
                'legal_reference': 'Lei 14.133/2021, Art. 70',
                'is_required': True,
                'order': 8,
            },
        ]
    },

    # =========================================================================
    # 7. TERMO DE ADJUDICACAO
    # =========================================================================
    {
        'name': 'Termo de Adjudicacao - Lei 14.133',
        'description': 'Termo de adjudicacao do objeto ao licitante vencedor conforme Lei 14.133/2021.',
        'document_type': 'termo_adjudicacao',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 71',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao_processo',
                'section_name': 'Identificacao do Processo',
                'description': 'Identificacao do processo licitatorio.',
                'instructions': 'Informe numero do processo, modalidade e objeto.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'fundamentacao',
                'section_name': 'Fundamentacao Legal',
                'description': 'Fundamentacao legal da adjudicacao.',
                'instructions': 'Fundamente com base na Lei 14.133/2021 e no edital.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'resultado_certame',
                'section_name': 'Resultado do Certame',
                'description': 'Resumo do resultado do certame.',
                'instructions': 'Apresente resumo da classificacao final e habilitacao.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'adjudicatario',
                'section_name': 'Identificacao do Adjudicatario',
                'description': 'Dados do licitante adjudicatario.',
                'instructions': 'Informe razao social, CNPJ, endereco e representante.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'objeto_adjudicado',
                'section_name': 'Objeto Adjudicado',
                'description': 'Descricao do objeto adjudicado.',
                'instructions': 'Descreva o objeto com itens, quantidades e valores.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'valor_adjudicado',
                'section_name': 'Valor Adjudicado',
                'description': 'Valor total da adjudicacao.',
                'instructions': 'Informe o valor total adjudicado por extenso.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'decisao',
                'section_name': 'Decisao de Adjudicacao',
                'description': 'Decisao formal de adjudicacao.',
                'instructions': 'Registre a decisao de adjudicar o objeto ao vencedor.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 7,
            },
        ]
    },

    # =========================================================================
    # 8. TERMO DE HOMOLOGACAO
    # =========================================================================
    {
        'name': 'Termo de Homologacao - Lei 14.133',
        'description': 'Termo de homologacao do processo licitatorio conforme Lei 14.133/2021.',
        'document_type': 'termo_homologacao',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 71',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao_processo',
                'section_name': 'Identificacao do Processo',
                'description': 'Identificacao do processo licitatorio.',
                'instructions': 'Informe numero do processo, modalidade e objeto.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'fundamentacao',
                'section_name': 'Fundamentacao Legal',
                'description': 'Fundamentacao legal da homologacao.',
                'instructions': 'Fundamente com base na Lei 14.133/2021 e legislacao correlata.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'analise_regularidade',
                'section_name': 'Analise de Regularidade',
                'description': 'Analise da regularidade do procedimento.',
                'instructions': 'Ateste a regularidade de todas as fases do procedimento.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'adjudicacao_ratificada',
                'section_name': 'Adjudicacao Ratificada',
                'description': 'Ratificacao da adjudicacao.',
                'instructions': 'Ratifique a adjudicacao realizada.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'vencedor_homologado',
                'section_name': 'Vencedor Homologado',
                'description': 'Dados do licitante vencedor homologado.',
                'instructions': 'Informe dados completos do vencedor e valor homologado.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'decisao_homologacao',
                'section_name': 'Decisao de Homologacao',
                'description': 'Decisao formal de homologacao.',
                'instructions': 'Registre a decisao de homologar o procedimento.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'providencias',
                'section_name': 'Providencias Subsequentes',
                'description': 'Providencias apos homologacao.',
                'instructions': 'Indique as providencias para celebracao do contrato.',
                'legal_reference': 'Lei 14.133/2021, Art. 71',
                'is_required': True,
                'order': 7,
            },
        ]
    },

    # =========================================================================
    # 9. RESPOSTA A IMPUGNACAO
    # =========================================================================
    {
        'name': 'Resposta a Impugnacao - Lei 14.133',
        'description': 'Resposta a impugnacao ao edital conforme Lei 14.133/2021.',
        'document_type': 'resposta_impugnacao',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 164',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao',
                'section_name': 'Identificacao',
                'description': 'Identificacao do processo e impugnacao.',
                'instructions': 'Informe processo, impugnante e protocolo da impugnacao.',
                'legal_reference': 'Lei 14.133/2021, Art. 164',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'relatorio',
                'section_name': 'Relatorio',
                'description': 'Sintese dos pontos impugnados.',
                'instructions': 'Resuma os pontos questionados pelo impugnante.',
                'legal_reference': 'Lei 14.133/2021, Art. 164',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'analise_merito',
                'section_name': 'Analise de Merito',
                'description': 'Analise dos argumentos apresentados.',
                'instructions': 'Analise ponto a ponto os argumentos do impugnante.',
                'legal_reference': 'Lei 14.133/2021, Art. 164',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'fundamentacao',
                'section_name': 'Fundamentacao Legal',
                'description': 'Fundamentacao legal da resposta.',
                'instructions': 'Fundamente a resposta com base na legislacao.',
                'legal_reference': 'Lei 14.133/2021, Art. 164',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'decisao',
                'section_name': 'Decisao',
                'description': 'Decisao sobre a impugnacao.',
                'instructions': 'Decida pelo PROVIMENTO, PROVIMENTO PARCIAL ou IMPROVIMENTO.',
                'legal_reference': 'Lei 14.133/2021, Art. 164, par. 2',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'providencias',
                'section_name': 'Providencias',
                'description': 'Providencias decorrentes da decisao.',
                'instructions': 'Se provida, indique alteracoes no edital e novo prazo.',
                'legal_reference': 'Lei 14.133/2021, Art. 164, par. 3',
                'is_required': False,
                'order': 6,
            },
        ]
    },

    # =========================================================================
    # 10. DECISAO DE RECURSO
    # =========================================================================
    {
        'name': 'Decisao de Recurso Administrativo - Lei 14.133',
        'description': 'Decisao de recurso administrativo conforme Lei 14.133/2021.',
        'document_type': 'decisao_recurso',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 165-168',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao',
                'section_name': 'Identificacao',
                'description': 'Identificacao do processo e recurso.',
                'instructions': 'Informe processo, recorrente e ato recorrido.',
                'legal_reference': 'Lei 14.133/2021, Art. 165',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'tempestividade',
                'section_name': 'Analise de Tempestividade',
                'description': 'Verificacao do prazo do recurso.',
                'instructions': 'Verifique se o recurso foi interposto no prazo legal.',
                'legal_reference': 'Lei 14.133/2021, Art. 165, par. 1',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'relatorio',
                'section_name': 'Relatorio',
                'description': 'Sintese do recurso e contrarrazoes.',
                'instructions': 'Resuma as razoes do recurso e eventuais contrarrazoes.',
                'legal_reference': 'Lei 14.133/2021, Art. 165',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'analise_merito',
                'section_name': 'Analise de Merito',
                'description': 'Analise do merito recursal.',
                'instructions': 'Analise cada argumento do recurso.',
                'legal_reference': 'Lei 14.133/2021, Art. 165',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'fundamentacao',
                'section_name': 'Fundamentacao Legal',
                'description': 'Fundamentacao da decisao.',
                'instructions': 'Fundamente a decisao com base na legislacao e jurisprudencia.',
                'legal_reference': 'Lei 14.133/2021, Art. 165-168',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'decisao',
                'section_name': 'Decisao',
                'description': 'Decisao do recurso.',
                'instructions': 'Decida pelo PROVIMENTO, PROVIMENTO PARCIAL ou IMPROVIMENTO.',
                'legal_reference': 'Lei 14.133/2021, Art. 168',
                'is_required': True,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'efeitos',
                'section_name': 'Efeitos da Decisao',
                'description': 'Efeitos praticos da decisao.',
                'instructions': 'Descreva os efeitos da decisao sobre o procedimento.',
                'legal_reference': 'Lei 14.133/2021, Art. 168',
                'is_required': True,
                'order': 7,
            },
        ]
    },

    # =========================================================================
    # 11. ORDEM DE SERVICO/FORNECIMENTO
    # =========================================================================
    {
        'name': 'Ordem de Servico/Fornecimento - Lei 14.133',
        'description': 'Ordem de servico ou fornecimento para inicio da execucao contratual.',
        'document_type': 'ordem_servico',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 90-91',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao',
                'section_name': 'Identificacao',
                'description': 'Identificacao do contrato e partes.',
                'instructions': 'Informe numero do contrato, contratante e contratado.',
                'legal_reference': 'Lei 14.133/2021, Art. 90',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'objeto',
                'section_name': 'Objeto',
                'description': 'Objeto da ordem.',
                'instructions': 'Descreva o servico/fornecimento a ser executado.',
                'legal_reference': 'Lei 14.133/2021, Art. 90',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'local_execucao',
                'section_name': 'Local de Execucao',
                'description': 'Local onde sera executado.',
                'instructions': 'Informe o local de execucao/entrega.',
                'legal_reference': 'Lei 14.133/2021, Art. 90',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'prazo',
                'section_name': 'Prazo de Execucao',
                'description': 'Prazo para execucao.',
                'instructions': 'Informe data de inicio e prazo para conclusao.',
                'legal_reference': 'Lei 14.133/2021, Art. 90',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'valor',
                'section_name': 'Valor',
                'description': 'Valor da ordem.',
                'instructions': 'Informe o valor desta ordem de servico/fornecimento.',
                'legal_reference': 'Lei 14.133/2021, Art. 90',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'responsaveis',
                'section_name': 'Responsaveis',
                'description': 'Responsaveis pela fiscalizacao.',
                'instructions': 'Informe fiscal e gestor do contrato.',
                'legal_reference': 'Lei 14.133/2021, Art. 117',
                'is_required': True,
                'order': 6,
            },
        ]
    },

    # =========================================================================
    # 12. TERMO DE RECEBIMENTO PROVISORIO
    # =========================================================================
    {
        'name': 'Termo de Recebimento Provisorio - Lei 14.133',
        'description': 'Termo de recebimento provisorio de obras, servicos ou compras.',
        'document_type': 'termo_recebimento_provisorio',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 140, inciso I, alinea a',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao',
                'section_name': 'Identificacao',
                'description': 'Identificacao do contrato.',
                'instructions': 'Informe numero do contrato, objeto e partes.',
                'legal_reference': 'Lei 14.133/2021, Art. 140',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'objeto_recebido',
                'section_name': 'Objeto Recebido',
                'description': 'Descricao do que esta sendo recebido.',
                'instructions': 'Descreva o objeto/servico entregue.',
                'legal_reference': 'Lei 14.133/2021, Art. 140, I, a',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'verificacao_inicial',
                'section_name': 'Verificacao Inicial',
                'description': 'Verificacao sumaria.',
                'instructions': 'Registre a verificacao quanto a quantidade e aparente conformidade.',
                'legal_reference': 'Lei 14.133/2021, Art. 140, I, a',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'ressalvas',
                'section_name': 'Ressalvas',
                'description': 'Ressalvas ou pendencias.',
                'instructions': 'Registre eventuais ressalvas ou pendencias identificadas.',
                'legal_reference': 'Lei 14.133/2021, Art. 140',
                'is_required': False,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'declaracao',
                'section_name': 'Declaracao de Recebimento',
                'description': 'Declaracao formal de recebimento provisorio.',
                'instructions': 'Declare o recebimento provisorio para posterior verificacao.',
                'legal_reference': 'Lei 14.133/2021, Art. 140, I, a',
                'is_required': True,
                'order': 5,
            },
        ]
    },

    # =========================================================================
    # 13. TERMO DE RECEBIMENTO DEFINITIVO
    # =========================================================================
    {
        'name': 'Termo de Recebimento Definitivo - Lei 14.133',
        'description': 'Termo de recebimento definitivo de obras, servicos ou compras.',
        'document_type': 'termo_recebimento_definitivo',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 140, inciso I, alinea b',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'identificacao',
                'section_name': 'Identificacao',
                'description': 'Identificacao do contrato.',
                'instructions': 'Informe numero do contrato, objeto e partes.',
                'legal_reference': 'Lei 14.133/2021, Art. 140',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'recebimento_provisorio',
                'section_name': 'Recebimento Provisorio',
                'description': 'Referencia ao recebimento provisorio.',
                'instructions': 'Referencie o termo de recebimento provisorio.',
                'legal_reference': 'Lei 14.133/2021, Art. 140, I, b',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'verificacao_detalhada',
                'section_name': 'Verificacao Detalhada',
                'description': 'Verificacao de qualidade e conformidade.',
                'instructions': 'Descreva a verificacao de qualidade e especificacoes.',
                'legal_reference': 'Lei 14.133/2021, Art. 140, I, b',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'ateste_conformidade',
                'section_name': 'Ateste de Conformidade',
                'description': 'Ateste de conformidade com o contrato.',
                'instructions': 'Ateste que o objeto esta em conformidade com o contratado.',
                'legal_reference': 'Lei 14.133/2021, Art. 140, I, b',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'declaracao_definitiva',
                'section_name': 'Declaracao de Recebimento Definitivo',
                'description': 'Declaracao formal de recebimento definitivo.',
                'instructions': 'Declare o recebimento definitivo do objeto.',
                'legal_reference': 'Lei 14.133/2021, Art. 140, I, b',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'autorizacao_pagamento',
                'section_name': 'Autorizacao de Pagamento',
                'description': 'Autorizacao para pagamento.',
                'instructions': 'Autorize o pagamento correspondente.',
                'legal_reference': 'Lei 14.133/2021, Art. 140',
                'is_required': True,
                'order': 6,
            },
        ]
    },

    # =========================================================================
    # 14. ADITIVO CONTRATUAL
    # =========================================================================
    {
        'name': 'Aditivo Contratual - Lei 14.133',
        'description': 'Termo aditivo ao contrato administrativo.',
        'document_type': 'aditivo_contratual',
        'version': '1.0',
        'legal_basis': 'Lei 14.133/2021, Art. 124-136',
        'is_active': True,
        'is_default': True,
        'sections': [
            {
                'section_number': 1,
                'section_key': 'preambulo',
                'section_name': 'Preambulo',
                'description': 'Identificacao das partes e contrato original.',
                'instructions': 'Identifique as partes e o contrato que sera aditado.',
                'legal_reference': 'Lei 14.133/2021, Art. 124',
                'is_required': True,
                'order': 1,
            },
            {
                'section_number': 2,
                'section_key': 'objeto_aditamento',
                'section_name': 'Objeto do Aditamento',
                'description': 'Descricao do que esta sendo aditado.',
                'instructions': 'Descreva o objeto do aditamento (prazo, valor, escopo).',
                'legal_reference': 'Lei 14.133/2021, Art. 124-125',
                'is_required': True,
                'order': 2,
            },
            {
                'section_number': 3,
                'section_key': 'justificativa',
                'section_name': 'Justificativa',
                'description': 'Justificativa para o aditamento.',
                'instructions': 'Justifique a necessidade do aditamento.',
                'legal_reference': 'Lei 14.133/2021, Art. 124',
                'is_required': True,
                'order': 3,
            },
            {
                'section_number': 4,
                'section_key': 'fundamentacao',
                'section_name': 'Fundamentacao Legal',
                'description': 'Base legal do aditamento.',
                'instructions': 'Fundamente com os artigos da Lei 14.133 aplicaveis.',
                'legal_reference': 'Lei 14.133/2021, Art. 124-136',
                'is_required': True,
                'order': 4,
            },
            {
                'section_number': 5,
                'section_key': 'clausulas_alteradas',
                'section_name': 'Clausulas Alteradas',
                'description': 'Clausulas do contrato original que serao alteradas.',
                'instructions': 'Liste as clausulas alteradas com redacao original e nova.',
                'legal_reference': 'Lei 14.133/2021, Art. 124',
                'is_required': True,
                'order': 5,
            },
            {
                'section_number': 6,
                'section_key': 'valor_aditado',
                'section_name': 'Valor Aditado',
                'description': 'Impacto financeiro do aditamento.',
                'instructions': 'Informe valores (acrescimo, supressao ou repactuacao).',
                'legal_reference': 'Lei 14.133/2021, Art. 125',
                'is_required': False,
                'order': 6,
            },
            {
                'section_number': 7,
                'section_key': 'prazo_aditado',
                'section_name': 'Prazo Aditado',
                'description': 'Alteracao de prazo.',
                'instructions': 'Informe prorrogacao ou alteracao de prazo.',
                'legal_reference': 'Lei 14.133/2021, Art. 111',
                'is_required': False,
                'order': 7,
            },
            {
                'section_number': 8,
                'section_key': 'disposicoes_finais',
                'section_name': 'Disposicoes Finais',
                'description': 'Clausulas finais do aditivo.',
                'instructions': 'Mantenha clausulas nao alteradas e define foro.',
                'legal_reference': 'Lei 14.133/2021, Art. 124',
                'is_required': True,
                'order': 8,
            },
        ]
    },
]


def create_blueprints(apps, schema_editor):
    """Cria os blueprints e suas secoes"""
    DocumentBlueprint = apps.get_model('intelligent_assistant', 'DocumentBlueprint')
    BlueprintSection = apps.get_model('intelligent_assistant', 'BlueprintSection')

    for bp_data in BLUEPRINTS_DATA:
        sections_data = bp_data.pop('sections')

        # Criar blueprint
        blueprint = DocumentBlueprint.objects.create(
            id=uuid.uuid4(),
            **bp_data
        )

        # Criar secoes
        for section_data in sections_data:
            BlueprintSection.objects.create(
                id=uuid.uuid4(),
                blueprint=blueprint,
                **section_data
            )

        print(f"  Criado: {blueprint.name} com {len(sections_data)} secoes")


def delete_blueprints(apps, schema_editor):
    """Remove os blueprints criados (rollback)"""
    DocumentBlueprint = apps.get_model('intelligent_assistant', 'DocumentBlueprint')

    types_to_delete = [bp['document_type'] for bp in BLUEPRINTS_DATA]
    DocumentBlueprint.objects.filter(document_type__in=types_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('intelligent_assistant', '0008_increase_document_type_maxlength'),
    ]

    operations = [
        migrations.RunPython(create_blueprints, delete_blueprints),
    ]
