# Generated by Django 5.0.1 on 2026-01-14 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0010_add_lei_14133_blueprints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_number", models.IntegerField(verbose_name="Número da Seção")),
                (
                    "section_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome da Seção"
                    ),
                ),
                (
                    "original_content",
                    models.TextField(
                        help_text="Conteúdo gerado pela IA",
                        verbose_name="Conteúdo Original",
                    ),
                ),
                (
                    "edited_content",
                    models.TextField(
                        help_text="Conteúdo após edição do usuário",
                        verbose_name="Conteúdo Editado",
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        help_text="Nota de 1 a 5 estrelas",
                        verbose_name="Avaliação do Usuário",
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        help_text="Score original da validação da IA (0-100)",
                        verbose_name="Score da IA",
                    ),
                ),
                (
                    "edit_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo da Edição"
                    ),
                ),
                (
                    "is_improvement",
                    models.BooleanField(
                        default=False,
                        help_text="True se o conteúdo editado é diferente do original",
                        verbose_name="É Melhoria",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Admin aprovou para usar em KB de melhorias",
                        verbose_name="Aprovado para KB",
                    ),
                ),
                (
                    "embedding_created",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o embedding foi criado na KB",
                        verbose_name="Embedding Criado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_feedbacks",
                        to="intelligent_assistant.intelligentsession",
                        verbose_name="Sessão",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback de Seção",
                "verbose_name_plural": "Feedbacks de Seções",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "section_number"],
                        name="intelligent_session_a123c6_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="intelligent_user_id_569557_idx",
                    ),
                    models.Index(
                        fields=["is_approved"], name="intelligent_is_appr_b0064b_idx"
                    ),
                ],
            },
        ),
    ]
