# Generated by Django 5.0.1 on 2026-02-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0013_blueprint_document_type_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentblueprint",
            options={
                "ordering": [
                    "document_type__display_order",
                    "document_type__name",
                    "name",
                ],
                "verbose_name": "Blueprint de Documento",
                "verbose_name_plural": "Blueprints de Documentos",
            },
        ),
        # Índice já foi recriado na migration 0013, apenas garantir que existe
        migrations.AddIndex(
            model_name="documentblueprint",
            index=models.Index(
                fields=["document_type", "is_active"],
                name="intelligent_documen_b64fcd_idx",
            ),
        ),
    ]
