# Generated by Django 5.0.1 on 2026-02-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0014_alter_documentblueprint_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentblueprint",
            name="intelligent_documen_7be6b6_idx",
        ),
        migrations.AddField(
            model_name="blueprintsection",
            name="section_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Campos estruturados para preenchimento. Exemplo:\n        [\n            {"name": "nome", "label": "Nome", "type": "text", "required": true},\n            {"name": "email", "label": "E-mail", "type": "email", "required": true}\n        ]\n        Tipos suportados: text, email, tel, number, date, select, textarea, array',
                verbose_name="Campos da Seção",
            ),
        ),
    ]
