# Generated by Django 5.0.1 on 2026-02-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0017_fix_dod_uppercase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgebase",
            options={
                "ordering": ["kb_layer", "name"],
                "verbose_name": "Base de Conhecimento",
                "verbose_name_plural": "Bases de Conhecimento",
            },
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="agent_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Agente de seção ao qual esta KB pertence (apenas para camada agent)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="improvement_kbs",
                to="intelligent_assistant.sectionagentconfig",
                verbose_name="Agente Associado",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="blueprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Blueprint ao qual esta KB pertence (apenas para camada blueprint)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledge_bases",
                to="intelligent_assistant.documentblueprint",
                verbose_name="Blueprint Associado",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="kb_layer",
            field=models.CharField(
                choices=[
                    ("global", "Global (Normas Gerais)"),
                    ("blueprint", "Blueprint (Base do Documento)"),
                    ("agent", "Agente (Melhores Resultados)"),
                ],
                default="global",
                help_text="Camada na hierarquia: global (todos acessam), blueprint (por tipo de documento), agent (melhores resultados)",
                max_length=20,
                verbose_name="Camada",
            ),
        ),
    ]
