# Generated by Django 5.0.1 on 2026-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0018_kb_3_layer_architecture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadeddocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="intelligent_assistant/uploads/%Y/%m/%d/",
                verbose_name="Arquivo",
            ),
        ),
    ]
