# Generated by Django 5.0.1 on 2026-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0020_add_watsonx_and_section_dependencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadeddocument",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document"),
                    ("odt", "OpenDocument Text"),
                    ("txt", "Texto"),
                ],
                max_length=10,
                verbose_name="Tipo de Arquivo",
            ),
        ),
    ]
