# Generated by Django 5.0.1 on 2026-02-20 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0023_generationsession_pipeline_graph"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número da Seção"
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nome da Seção",
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("generate", "Geração"),
                            ("validate", "Validação"),
                            ("regenerate", "Regeneração"),
                            ("other", "Outro"),
                        ],
                        default="generate",
                        max_length=20,
                        verbose_name="Tipo de Chamada",
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(default=1, verbose_name="Número da Tentativa"),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="anthropic, openai, watsonx",
                        max_length=50,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Ex: claude-haiku-4-5, gpt-4o-mini",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "input_tokens",
                    models.IntegerField(default=0, verbose_name="Tokens de Entrada"),
                ),
                (
                    "output_tokens",
                    models.IntegerField(default=0, verbose_name="Tokens de Saída"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="input_tokens + output_tokens",
                        verbose_name="Total de Tokens",
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Tempo de execução da chamada em milissegundos",
                        verbose_name="Duração (ms)",
                    ),
                ),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Custo estimado baseado nos preços do provider/modelo",
                        max_digits=10,
                        verbose_name="Custo Estimado (USD)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria LLM",
                "verbose_name_plural": "Logs de Auditoria LLM",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="agentknowledgebaselink",
            new_name="intelligent_agent_i_be96d3_idx",
            old_name="ia_agentkblink_agent_priority_idx",
        ),
        migrations.RenameIndex(
            model_name="agentknowledgebaselink",
            new_name="intelligent_is_acti_a38a63_idx",
            old_name="ia_agentkblink_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="sectionpipelinestep",
            new_name="intelligent_section_a4c992_idx",
            old_name="ia_pipelinestep_section_order_idx",
        ),
        migrations.AddField(
            model_name="generationsession",
            name="estimated_cost_usd",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Custo estimado baseado nos preços do provider/modelo",
                max_digits=10,
                verbose_name="Custo Estimado (USD)",
            ),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="total_input_tokens",
            field=models.IntegerField(
                default=0,
                help_text="Soma de input_tokens de todas as chamadas LLM desta sessão",
                verbose_name="Total Tokens de Entrada",
            ),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="total_output_tokens",
            field=models.IntegerField(
                default=0,
                help_text="Soma de output_tokens de todas as chamadas LLM desta sessão",
                verbose_name="Total Tokens de Saída",
            ),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="total_tokens",
            field=models.IntegerField(
                default=0,
                help_text="Soma total (input + output) de todas as chamadas LLM desta sessão",
                verbose_name="Total de Tokens",
            ),
        ),
        migrations.AddField(
            model_name="llmauditlog",
            name="blueprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_audit_logs",
                to="intelligent_assistant.documentblueprint",
                verbose_name="Blueprint",
            ),
        ),
        migrations.AddField(
            model_name="llmauditlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_audit_logs",
                to="intelligent_assistant.generationsession",
                verbose_name="Sessão de Geração",
            ),
        ),
        migrations.AddField(
            model_name="llmauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddIndex(
            model_name="llmauditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="intelligent_user_id_cdc82c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmauditlog",
            index=models.Index(
                fields=["session"], name="intelligent_session_c1d1b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmauditlog",
            index=models.Index(
                fields=["blueprint", "-created_at"],
                name="intelligent_bluepri_55a474_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmauditlog",
            index=models.Index(
                fields=["provider", "model"], name="intelligent_provide_ebe972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmauditlog",
            index=models.Index(
                fields=["call_type", "-created_at"],
                name="intelligent_call_ty_6f082a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmauditlog",
            index=models.Index(
                fields=["-created_at"], name="intelligent_created_eec1a7_idx"
            ),
        ),
    ]
