# Generated by Django 5.0.1 on 2026-02-22 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0024_add_llm_audit_log_and_session_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintSubSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sub_number",
                    models.CharField(
                        help_text='Numeração do sub-item (ex: "4.1", "4.2", "3.1")',
                        max_length=20,
                        verbose_name="Numeração",
                    ),
                ),
                (
                    "sub_name",
                    models.CharField(
                        help_text='Nome do sub-item (ex: "Requisitos de Negócio")',
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "sub_key",
                    models.CharField(
                        help_text='Identificador único dentro do blueprint (ex: "requisitos_negocio")',
                        max_length=100,
                        verbose_name="Chave",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do que deve conter este sub-item",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text='Orientação ao usuário sobre o que preencher quando escolher "Sim, detalhar"',
                        verbose_name="Texto de Ajuda",
                    ),
                ),
                (
                    "default_text",
                    models.TextField(
                        blank=True,
                        help_text='Texto inserido automaticamente quando o usuário escolhe "Não se aplica". Ex: "Não foi identificada necessidade de capacitação/treinamento específico."',
                        verbose_name="Texto Padrão (OU)",
                    ),
                ),
                (
                    "section_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Campos que o usuário preenche antes da geração por IA. Mesma estrutura de BlueprintSection.section_fields.",
                        verbose_name="Campos de Input",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Ordem de exibição dentro da seção pai",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text='Se True, o usuário não pode escolher "Não se aplica"',
                        verbose_name="Obrigatório",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "generator_agent",
                    models.ForeignKey(
                        blank=True,
                        help_text='Agente que gera o conteúdo quando o usuário escolhe "Sim, detalhar"',
                        limit_choices_to={"agent_type": "generator", "is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generator_for_sub_sections",
                        to="intelligent_assistant.sectionagentconfig",
                        verbose_name="Agente Gerador",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_sections",
                        to="intelligent_assistant.blueprintsection",
                        verbose_name="Seção Pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-seção do Blueprint",
                "verbose_name_plural": "Sub-seções do Blueprint",
                "ordering": ["section", "order", "sub_number"],
                "indexes": [
                    models.Index(
                        fields=["section", "order"],
                        name="intelligent_section_2bfce2_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="intelligent_is_acti_9b9923_idx"
                    ),
                ],
                "unique_together": {("section", "sub_key")},
            },
        ),
    ]
