# Generated by Django 5.0.1 on 2026-02-23 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0025_add_blueprint_sub_section"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KBSourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Arquivo original armazenado no R2",
                        null=True,
                        upload_to="kb/sources/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nome do Arquivo"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="Tamanho (bytes)"),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="pdf, docx, odt, txt...",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Categoria"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "chunk_count",
                    models.IntegerField(default=0, verbose_name="Chunks Gerados"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Processado"),
                            ("failed", "Falha"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, default="", verbose_name="Erro"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="intelligent_assistant.knowledgebase",
                        verbose_name="Base de Conhecimento",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_source_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo-Fonte da KB",
                "verbose_name_plural": "Arquivos-Fonte da KB",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["knowledge_base", "status"],
                        name="intelligent_knowled_0d5cab_idx",
                    )
                ],
            },
        ),
    ]
