# Generated by Django 5.0.1 on 2026-02-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0027_migrate_kb_data_to_unified"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentknowledgebaselink",
            name="selected_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de nomes de fontes (source_name) que o agente pode acessar. Vazio = todas as fontes.",
                verbose_name="Fontes Selecionadas",
            ),
        ),
    ]
