# Generated by Django 5.2.11 on 2026-03-12 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0030_kb_source_file_fk_and_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionImportConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("copy", "Cópia direta"),
                            ("transform", "Transformação IA"),
                            ("fixed", "Texto padrão"),
                            ("fixed_ia", "Padrão + IA"),
                            ("input", "Manual"),
                            ("ou", "OU (alternativas)"),
                            ("mixed", "Misto (ETP + Padrão)"),
                        ],
                        db_index=True,
                        help_text="Como o conteúdo será tratado na importação",
                        max_length=20,
                        verbose_name="Tipo de Importação",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Descrição legível do mapeamento (ex: "ETP §1 + §9")',
                        max_length=200,
                        verbose_name="Rótulo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Ativo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "source_sections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Seções do blueprint fonte de onde importar conteúdo",
                        related_name="export_targets",
                        to="intelligent_assistant.blueprintsection",
                        verbose_name="Seções Fonte",
                    ),
                ),
                (
                    "target_section",
                    models.OneToOneField(
                        help_text="Seção do blueprint que recebe o conteúdo importado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_config",
                        to="intelligent_assistant.blueprintsection",
                        verbose_name="Seção Alvo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Importação",
                "verbose_name_plural": "Configurações de Importação",
                "ordering": ["target_section__section_number"],
            },
        ),
    ]
