# Generated by Django 5.2.11 on 2026-03-16 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0031_add_section_import_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationsession",
            name="intelligent_session",
            field=models.OneToOneField(
                blank=True,
                help_text="Sessão do sistema legado, se existir",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dynamic_generation",
                to="intelligent_assistant.intelligentsession",
                verbose_name="Sessão Inteligente",
            ),
        ),
    ]
