# Generated by Django 5.2.11 on 2026-03-17 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "intelligent_assistant",
            "0032_cascade_generation_session_on_intelligent_session_delete",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationsession",
            name="intelligent_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Sessão do sistema legado, se existir",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_sessions",
                to="intelligent_assistant.intelligentsession",
                verbose_name="Sessão Inteligente",
            ),
        ),
    ]
