# Generated by Django 5.2.11 on 2026-03-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0033_onetoonefield_to_fk_generation_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintsubsection",
            name="source_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Seção de outro blueprint (ex: TR) de onde importar conteúdo para esta sub-seção",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_by_sub_sections",
                to="intelligent_assistant.blueprintsection",
                verbose_name="Seção Fonte (import)",
            ),
        ),
        migrations.AddField(
            model_name="blueprintsubsection",
            name="source_sub_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Sub-seção de outro blueprint (ex: TR §4.1) de onde importar conteúdo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_by_sub_sections",
                to="intelligent_assistant.blueprintsubsection",
                verbose_name="Sub-seção Fonte (import)",
            ),
        ),
    ]
