# Generated by Django 5.2.11 on 2026-03-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0034_add_source_import_to_blueprintsubsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intelligentsession",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("DOD", "Documento de Oficialização de Demanda"),
                    ("dfd", "Documento de Formalização de Demanda"),
                    ("etp", "Estudo Técnico Preliminar"),
                    ("termo_referencia", "Termo de Referência"),
                    ("projeto_basico", "Projeto Básico"),
                    ("projeto_executivo", "Projeto Executivo"),
                    ("mapa_riscos", "Mapa de Riscos"),
                    ("pesquisa_precos", "Pesquisa de Preços"),
                    ("edital", "Edital de Licitação"),
                    ("contrato", "Contrato"),
                    ("minuta_contrato", "Minuta de Contrato"),
                    ("ata_sessao", "Ata de Sessão Pública"),
                    ("parecer_julgamento", "Parecer de Julgamento"),
                    ("parecer_habilitacao", "Parecer de Habilitação"),
                    ("termo_adjudicacao", "Termo de Adjudicação"),
                    ("termo_homologacao", "Termo de Homologação"),
                    ("impugnacao", "Impugnação ao Edital"),
                    ("resposta_impugnacao", "Resposta à Impugnação"),
                    ("recurso", "Recurso Administrativo"),
                    ("contrarrazoes", "Contrarrazões de Recurso"),
                    ("decisao_recurso", "Decisão de Recurso"),
                    ("parecer", "Parecer Técnico"),
                    ("parecer_juridico", "Parecer Jurídico"),
                    ("ordem_servico", "Ordem de Serviço/Fornecimento"),
                    ("termo_recebimento_provisorio", "Termo de Recebimento Provisório"),
                    ("termo_recebimento_definitivo", "Termo de Recebimento Definitivo"),
                    ("aditivo_contratual", "Aditivo Contratual"),
                    ("custom", "Customizado"),
                ],
                default="etp",
                max_length=50,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
