# Generated by Django 5.2.11 on 2026-03-24 22:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0035_add_minuta_contrato_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome único do tool (ex: Web Search (Serper))",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("web_search", "Busca Web (Serper/Google)"),
                            ("pncp_search", "Busca PNCP (contratos/editais)"),
                            ("custom", "Custom (serviço externo)"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="O que este tool faz e quando usar",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "service_path",
                    models.CharField(
                        help_text="Ex: apps.price_research.services.web_search_service.WebSearchService",
                        max_length=200,
                        verbose_name="Caminho do Service",
                    ),
                ),
                (
                    "method_name",
                    models.CharField(
                        default="search",
                        help_text="Método a chamar no service (ex: search, _search_pncp)",
                        max_length=50,
                        verbose_name="Método",
                    ),
                ),
                (
                    "default_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Config padrão em JSON: {"max_results": 10, "timeout": 25}',
                        verbose_name="Configuração Padrão",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Ativo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Agent Tool",
                "verbose_name_plural": "Agent Tools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentToolLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Ordem de execução (menor = primeiro)",
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "custom_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Override da config padrão do tool (ex: {"max_results": 5})',
                        verbose_name="Config Customizada",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Habilitado"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_links",
                        to="intelligent_assistant.sectionagentconfig",
                        verbose_name="Agente",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_links",
                        to="intelligent_assistant.agenttool",
                        verbose_name="Tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo Agente ↔ Tool",
                "verbose_name_plural": "Vínculos Agente ↔ Tool",
                "ordering": ["priority"],
                "unique_together": {("agent", "tool")},
            },
        ),
    ]
