# Generated by Django 5.2.11 on 2026-04-27 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligent_assistant", "0036_add_agent_tools"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="intelligentsession",
            name="parent_etp_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Quando esta sessão é um anexo do ETP, aponta para a sessão do ETP a que pertence.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_attachments",
                to="intelligent_assistant.intelligentsession",
                verbose_name="ETP pai (anexo)",
            ),
        ),
        migrations.AlterField(
            model_name="intelligentsession",
            name="document_type",
            field=models.CharField(
                default="etp",
                help_text="Code do core.DocumentType. Validação dinâmica via tabela centralizada.",
                max_length=50,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddIndex(
            model_name="intelligentsession",
            index=models.Index(
                fields=["parent_etp_session"], name="intelligent_parent__145432_idx"
            ),
        ),
    ]
