# Generated by Django 5.2.11 on 2026-04-30 03:54
"""
Limpa duplicatas de anexos (mesma session-pai + mesmo tipo + mesmo user)
mantendo o registro MAIS ANTIGO de cada grupo, e adiciona UniqueConstraint
condicional para impedir novas duplicatas.

Idempotente: se nao houver duplicatas, RunPython nao faz nada.

Em homolog, as 4 duplicatas pre-existentes ja foram limpas manualmente
em 2026-04-30 (autorizado pelo PO).
"""

from django.conf import settings
from django.db import migrations, models


def cleanup_attachment_duplicates(apps, schema_editor):
    """
    Apaga duplicatas mantendo o registro com created_at mais antigo de cada
    grupo (parent_etp_session, document_type, user). Cascata remove
    GeneratedDocument, GenerationSession, etc. associados as duplicatas.
    """
    from django.db.models import Count, Min

    IntelligentSession = apps.get_model('intelligent_assistant', 'IntelligentSession')

    # Identifica grupos com mais de 1 sessao (anexos duplicados)
    duplicate_groups = (
        IntelligentSession.objects
        .filter(parent_etp_session__isnull=False)
        .values('parent_etp_session', 'document_type', 'user')
        .annotate(group_count=Count('id'), oldest_created=Min('created_at'))
        .filter(group_count__gt=1)
    )

    total_groups = duplicate_groups.count()
    if total_groups == 0:
        print('  [migration 0038] Nenhuma duplicata encontrada — segue.')
        return

    total_deleted = 0
    for group in duplicate_groups:
        # Mantem o de menor created_at; deleta os outros
        keepers = IntelligentSession.objects.filter(
            parent_etp_session_id=group['parent_etp_session'],
            document_type=group['document_type'],
            user_id=group['user'],
            created_at=group['oldest_created'],
        ).order_by('created_at').values_list('id', flat=True)
        keeper_id = list(keepers)[0]

        to_delete = IntelligentSession.objects.filter(
            parent_etp_session_id=group['parent_etp_session'],
            document_type=group['document_type'],
            user_id=group['user'],
        ).exclude(id=keeper_id)

        deleted_ids = list(to_delete.values_list('id', flat=True))
        deleted_count = to_delete.count()
        to_delete.delete()
        total_deleted += deleted_count

        print(
            f"  [migration 0038] grupo parent={group['parent_etp_session']} "
            f"type={group['document_type']} user={group['user']}: "
            f"mantido={keeper_id} deletados={deleted_ids}"
        )

    print(
        f'  [migration 0038] Total: {total_groups} grupos, '
        f'{total_deleted} sessoes deletadas (cascata removeu '
        f'GeneratedDocument/GenerationSession/etc).'
    )


def noop_reverse(apps, schema_editor):
    """Reverter a limpeza nao restaura sessoes deletadas."""
    pass


class Migration(migrations.Migration):

    # IMPORTANTE: atomic=False eh obrigatorio aqui.
    # RunPython faz DELETE com FK CASCADE -> Postgres registra triggers
    # de cascade pendentes na transacao. AddConstraint depois nao consegue
    # criar INDEX enquanto houver triggers pendentes (erro "cannot CREATE
    # INDEX ... because it has pending trigger events" — bateu em prod
    # 2026-04-30 quando havia 2 anexos duplicados pre-existentes).
    # atomic=False quebra em transacoes separadas: RunPython commita,
    # triggers rodam, AddConstraint cria indice limpo.
    # Idempotente: re-rodar e seguro (RunPython acha 0 duplicatas).
    atomic = False

    dependencies = [
        (
            "intelligent_assistant",
            "0037_intelligentsession_parent_etp_session_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            cleanup_attachment_duplicates,
            reverse_code=noop_reverse,
        ),
        migrations.AddConstraint(
            model_name="intelligentsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent_etp_session__isnull", False)),
                fields=("parent_etp_session", "document_type", "user"),
                name="unique_attachment_per_parent_type_user",
            ),
        ),
    ]
