# Generated by Django 5.2.11 on 2026-05-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligent_assistant', '0038_unique_attachment_per_parent_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttool',
            name='service_path',
            field=models.CharField(help_text='Ex: apps.intelligent_assistant.services.tools.web_search_tool.WebSearchTool', max_length=200, verbose_name='Caminho do Service'),
        ),
    ]
