# Generated by Django 5.0.14 on 2026-05-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligent_assistant', '0042_add_blueprint_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentblueprint',
            name='primary_color',
            field=models.CharField(default='#7030A0', help_text='Cor principal dos títulos (formato hex: #RRGGBB)', max_length=7, verbose_name='Cor Primária'),
        ),
        migrations.AlterField(
            model_name='documentblueprint',
            name='secondary_color',
            field=models.CharField(default='#5B2EE0', help_text='Cor dos subtítulos e destaques (formato hex: #RRGGBB)', max_length=7, verbose_name='Cor Secundária'),
        ),
        migrations.AlterField(
            model_name='intelligentsession',
            name='document_type',
            field=models.CharField(default='peticao_inicial', help_text='Code do core.DocumentType. Validação dinâmica via tabela centralizada.', max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='intelligentsession',
            name='parent_etp_session',
            field=models.ForeignKey(blank=True, help_text='Quando esta sessão é um anexo de outra, aponta para a sessão principal a que pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_attachments', to='intelligent_assistant.intelligentsession', verbose_name='Sessão pai (anexo)'),
        ),
        migrations.AlterField(
            model_name='intelligentsession',
            name='status',
            field=models.CharField(choices=[('initialized', 'Inicializada'), ('collecting_data', 'Coletando Dados'), ('uploading', 'Upload de Documentos'), ('processing', 'Processando Documentos'), ('generating', 'Gerando Seções'), ('validating', 'Validando'), ('formatting', 'Formatando'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='initialized', max_length=20, verbose_name='Status'),
        ),
    ]
